using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Web.Script.Serialization;
using System.Windows.Forms;
namespace Velixa {
public static class DeskGeometry {
 public static RectangleF Bounds(double x,double y,int width,int height,double scale=1){width=Math.Max(1,width);height=Math.Max(1,height);float factor=(float)(220*Math.Max(.25,Math.Min(3,scale)))/Math.Max(width,height);return new RectangleF((float)x,(float)y,width*factor,height*factor);}
 public static int Find(List<RectangleF> r,int current,string direction,double ratio,Func<int,bool> online,out double nextRatio){nextRatio=ratio;if(current<0||current>=r.Count||Double.IsNaN(ratio)||Double.IsInfinity(ratio))return -1;var a=r[current];bool h=direction=="left"||direction=="right";float cross=(h?a.Top:a.Left)+(float)Math.Max(0,Math.Min(1,ratio))*(h?a.Height:a.Width);int best=-1;float distance=Single.MaxValue;
  for(int i=0;i<r.Count;i++){if(i==current||!online(i))continue;var b=r[i];float gap=direction=="right"?b.Left-a.Right:direction=="left"?a.Left-b.Right:direction=="bottom"?b.Top-a.Bottom:a.Top-b.Bottom;float low=h?b.Top:b.Left,high=h?b.Bottom:b.Right;if(Math.Abs(gap)>.75f||cross<low||cross>=high||gap>=distance)continue;distance=gap;best=i;nextRatio=(cross-low)/(high-low);}return best;
 }
  public static PointF Snap(RectangleF moving,IEnumerable<RectangleF> others){
   var all=others.ToList();if(all.Count==0)return moving.Location;var candidates=new List<PointF>();
   foreach(var b in all){
    float topY=b.Top,botY=b.Bottom-moving.Height,midY=b.Top+(b.Height-moving.Height)/2f;
    float cy=Math.Max(b.Top-moving.Height+1,Math.Min(b.Bottom-1,moving.Y));
    if(Math.Abs(cy-topY)<20)cy=topY;else if(Math.Abs(cy-botY)<20)cy=botY;else if(Math.Abs(cy-midY)<20)cy=midY;
    foreach(float y in new[]{topY,midY,botY,cy}){candidates.Add(new PointF(b.Right,y));candidates.Add(new PointF(b.Left-moving.Width,y));}
    float leftX=b.Left,rightX=b.Right-moving.Width,midX=b.Left+(b.Width-moving.Width)/2f;
    float cx=Math.Max(b.Left-moving.Width+1,Math.Min(b.Right-1,moving.X));
    if(Math.Abs(cx-leftX)<20)cx=leftX;else if(Math.Abs(cx-rightX)<20)cx=rightX;else if(Math.Abs(cx-midX)<20)cx=midX;
    foreach(float x in new[]{leftX,midX,rightX,cx}){candidates.Add(new PointF(x,b.Bottom));candidates.Add(new PointF(x,b.Top-moving.Height));}
   }
   return candidates.Where(v=>!all.Any(b=>Overlaps(new RectangleF(v,moving.Size),b))).OrderBy(v=>CandidateScore(v,moving,all)).First();
  }
  static float CandidateScore(PointF v,RectangleF moving,List<RectangleF> all){
   float dx=v.X-moving.X,dy=v.Y-moving.Y;float score=dx*dx+dy*dy;
   foreach(var b in all){
    bool alignedX=Math.Abs(v.X-b.Left)<.01f||Math.Abs(v.X-(b.Right-moving.Width))<.01f||Math.Abs(v.X-(b.Left+(b.Width-moving.Width)/2f))<.01f;
    bool alignedY=Math.Abs(v.Y-b.Top)<.01f||Math.Abs(v.Y-(b.Bottom-moving.Height))<.01f||Math.Abs(v.Y-(b.Top+(b.Height-moving.Height)/2f))<.01f;
    if(alignedX)score-=300f;if(alignedY)score-=300f;
   }
   return score;
  }
 public static bool Overlaps(RectangleF a,RectangleF b){return Math.Min(a.Right,b.Right)-Math.Max(a.Left,b.Left)>.01f&&Math.Min(a.Bottom,b.Bottom)-Math.Max(a.Top,b.Top)>.01f;}
 public static bool Segment(RectangleF a,RectangleF b,string side,out double from,out double to){bool h=side=="left"||side=="right";float gap=side=="left"?a.Left-b.Right:side=="right"?b.Left-a.Right:side=="top"?a.Top-b.Bottom:b.Top-a.Bottom;float low=Math.Max(h?a.Top:a.Left,h?b.Top:b.Left),high=Math.Min(h?a.Bottom:a.Right,h?b.Bottom:b.Right);from=(low-(h?a.Top:a.Left))/(h?a.Height:a.Width);to=(high-(h?a.Top:a.Left))/(h?a.Height:a.Width);return Math.Abs(gap)<=.75f&&high>low;}

}
public class Device {
 public string id,name,kind;public int w=1920,h=1080;public double x,y;public bool sharing,touchpad;public bool online;public bool sleeping;public bool awake=true;public double scale=1;
 [ScriptIgnore] public bool Available{get{return online&&awake&&!sleeping;}}
 [ScriptIgnore] public RectangleF Bounds{get{return DeskGeometry.Bounds(x,y,w,h,scale);}}
}
public class DeskProfile {public string id,name;public List<Device> devices=new List<Device>();}
public class DeskStore {public bool automatic=true;public string active;public List<DeskProfile> desks=new List<DeskProfile>();}
public class DeskSession : IDisposable {
 public List<Device> Devices=new List<Device>();public DeskStore Store=new DeskStore();public string DeskName{get{var p=Store.desks.Find(v=>v.id==Store.active);return p==null?"My desk":p.name;}}public volatile string Source="";public long Epoch;public InputController Input=new InputController();public Action Changed;public bool Automatic{get{return Store.automatic;}}
 readonly HashSet<string> pendingRemovals=new HashSet<string>();
 public bool Paused;
 readonly Network network;readonly Receiver receiver;readonly Action<Action> ui;DateTime lastActivity=DateTime.MinValue;public volatile bool Connected;public bool Preview;volatile bool localAvailable;public Action<string,Dictionary<string,object>> Shared;
 public DeskSession(Network n,Receiver r,Action<Action> dispatch){network=n;receiver=r;ui=dispatch;Input.PhysicalActivity=()=>{if(Paused||!Connected||Preview||!Automatic||Source==Network.LocalId||(DateTime.UtcNow-lastActivity).TotalMilliseconds<250)return;lastActivity=DateTime.UtcNow;ui(()=>{if(!Paused&&Connected&&!Preview&&Automatic&&Source!=Network.LocalId)SelectSource(Network.LocalId);});};Input.Changed=()=>{if(Changed!=null)Changed();};}
 public void RestoreClient(){try{Devices=new JavaScriptSerializer().Deserialize<List<Device>>(Wire.LoadSecret("client-devices.bin","[]"));foreach(var d in Devices)d.online=d.id==Network.LocalId;foreach(var id in new JavaScriptSerializer().Deserialize<List<string>>(Wire.LoadSecret("pending-removals.bin","[]")))pendingRemovals.Add(id);Devices.RemoveAll(d=>pendingRemovals.Contains(d.id));}catch{}Input.Enabled=false;}
 public void Host(){try{Devices=new JavaScriptSerializer().Deserialize<List<Device>>(Wire.LoadSecret("desk-v2.bin","[]"));}catch{}try{Store=new JavaScriptSerializer().Deserialize<DeskStore>(Wire.LoadSecret("desks-v3.bin","{}"));if(Store==null||Store.desks==null)Store=new DeskStore();var saved=Store.desks.Find(v=>v.id==Store.active);if(saved!=null)Devices=saved.devices;}catch{Store=new DeskStore();}foreach(var d in Devices){d.online=false;d.awake=true;}var local=Devices.Find(d=>d.id==Network.LocalId);if(local==null){local=new Device{id=Network.LocalId,name=Environment.MachineName,kind="Windows"};Devices.Insert(0,local);}local.online=true;local.sharing=true;local.touchpad=Wire.TouchpadAvailable;local.name=Environment.MachineName;var bounds=SystemInformation.VirtualScreen;local.w=bounds.Width;local.h=bounds.Height;Source=local.id;Connected=true;Epoch=1;Normalize();EnsureSource();
  network.Joined=p=>ui(()=>{if(p.Closed)return;var d=Devices.Find(v=>v.id==p.Id);if(d==null){d=new Device{id=p.Id,scale=p.Kind=="Android"?.5:1,x=Devices.Count==0?0:Devices.Max(v=>v.Bounds.Right)};Devices.Add(d);}d.name=p.Name;d.kind=p.Kind;d.sharing=p.Sharing;d.touchpad=p.Touchpad;d.w=p.Width;d.h=p.Height;d.online=true;d.awake=true;Normalize();Publish();});
  network.Left=p=>ui(()=>{if(network.Snapshot().Any(v=>v.Id==p.Id))return;var d=Devices.Find(v=>v.id==p.Id);if(d!=null)d.online=false;Reset();EnsureSource();Publish();});network.Packet=(p,m)=>{if(Wire.S(m,"t")=="route"&&Wire.S(m,"id")==Network.LocalId){object value;if(!Paused&&Connected&&!p.Closed&&localAvailable&&p.Kind=="Windows"&&p.Id==Source&&Wire.S(m,"epoch")==System.Threading.Interlocked.Read(ref Epoch).ToString()&&m.TryGetValue("event",out value)&&value is Dictionary<string,object>&&ValidEvent((Dictionary<string,object>)value)){long epoch=System.Threading.Interlocked.Read(ref Epoch);string sender=p.Id;receiver.Handle((Dictionary<string,object>)value,()=>!Paused&&Connected&&localAvailable&&Source==sender&&System.Threading.Interlocked.Read(ref Epoch)==epoch);}return;}ui(()=>HandlePeer(p,m));};Publish();
 }
 object State(){return new{t="desk",source=Source,epoch=Epoch,devices=Devices,desk=Store.active,deskName=DeskName,automatic=Automatic,desks=Store.desks.Select(v=>new{id=v.id,name=v.name}).ToArray()};}
 void Publish(bool save=true){if(save)SaveProfiles();Apply();foreach(var p in network.Snapshot())p.Send(State());}
 void Apply(){localAvailable=Devices.Any(d=>d.id==Network.LocalId&&d.Available);Input.Home();Input.Order.Clear();foreach(var d in Devices){if(d.id==Network.LocalId){Input.LocalX=d.x;Input.LocalY=d.y;Input.LocalScale=d.scale;Input.Order.Add(null);}else{string id=d.id;Input.Order.Add(new Peer{Id=id,Name=d.name,Kind=d.kind,Touchpad=d.touchpad,Width=d.w,Height=d.h,X=d.x,Y=d.y,Online=d.Available,Scale=d.scale,SendAction=o=>Route(id,o)});}}if(!Devices.Any(d=>d.id==Network.LocalId))Input.Order.Insert(0,null);Input.Enabled=!Paused&&!Preview&&Connected&&Source==Network.LocalId&&Devices.Any(d=>d.id==Network.LocalId&&d.Available);if(Changed!=null)Changed();}
 void Reset(){Input.Home();receiver.Handle(Wire.Parse("{\"t\":\"leave\"}"));foreach(var p in network.Snapshot())p.Send(new{t="leave"});System.Threading.Interlocked.Increment(ref Epoch);}
 public void SetAutomatic(bool enabled){if(!Connected)return;if(!network.IsHost){network.Send(new{t="automatic",enabled=enabled});return;}if(Store.automatic==enabled)return;Store.automatic=enabled;Publish();}
 public void UseSource(string id){if(!Connected)return;if(!network.IsHost){network.Send(new{t="fixed-source",id=id});return;}if(!Devices.Any(d=>d.id==id&&d.Available&&d.kind=="Windows"))return;Store.automatic=false;Reset();Source=id;Publish();}
 public void SelectSource(string id){if(!Connected)return;if(!network.IsHost){network.Send(new{t="source",id=id});return;}var d=Devices.Find(v=>v.id==id);if(d==null||!d.Available||d.kind!="Windows"||Source==id)return;Reset();Source=id;Publish(false);}
 public void Position(string id,double x,double y){if(!Connected||Double.IsNaN(x)||Double.IsNaN(y)||Double.IsInfinity(x)||Double.IsInfinity(y))return;x=Math.Max(-5000,Math.Min(5000,x));y=Math.Max(-5000,Math.Min(5000,y));if(!network.IsHost){network.Send(new{t="layout",id=id,x=x,y=y});return;}var d=Devices.Find(v=>v.id==id);if(d==null)return;var point=DeskGeometry.Snap(new RectangleF((float)x,(float)y,d.Bounds.Width,d.Bounds.Height),Devices.Where(v=>v!=d).Select(v=>v.Bounds));d.x=point.X;d.y=point.Y;Reset();Publish();}
  void Normalize(){var placed=new List<RectangleF>();foreach(var d in Devices){double lo,hi;if(placed.Count>0&&!placed.Any(b=>DeskGeometry.Overlaps(d.Bounds,b))&&placed.Any(b=>new[]{"left","right","top","bottom"}.Any(s=>DeskGeometry.Segment(d.Bounds,b,s,out lo,out hi)))){placed.Add(d.Bounds);continue;}var point=DeskGeometry.Snap(d.Bounds,placed);d.x=point.X;d.y=point.Y;placed.Add(d.Bounds);}}
 void SaveProfiles(){var p=Store.desks.Find(v=>v.id==Store.active);if(p==null){p=new DeskProfile{id=Guid.NewGuid().ToString(),name="My desk"};Store.desks.Add(p);Store.active=p.id;}p.devices=Devices;if(!Preview)Wire.SaveSecret("desks-v3.bin",Wire.Json(Store));}
 public void Profile(string action,string value){if(!Connected)return;if(!network.IsHost){network.Send(new{t="profile",action=action,value=value});return;}SaveProfiles();if(action=="create"){if(Store.desks.Count>=12)return;var p=new DeskProfile{id=Guid.NewGuid().ToString(),name=CleanName(value),devices=new JavaScriptSerializer().Deserialize<List<Device>>(Wire.Json(Devices))};Store.desks.Add(p);Store.active=p.id;Devices=p.devices;}else if(action=="switch"){var p=Store.desks.Find(v=>v.id==value);if(p==null)return;foreach(var current in Devices){var d=p.devices.Find(v=>v.id==current.id);if(d==null){d=new Device{id=current.id,scale=current.scale,x=p.devices.Count==0?0:p.devices.Max(v=>v.Bounds.Right),sleeping=true};p.devices.Add(d);}d.sharing=current.sharing;d.touchpad=current.touchpad;d.online=current.online;d.awake=current.awake;d.name=current.name;d.kind=current.kind;d.w=current.w;d.h=current.h;}Store.active=p.id;Devices=p.devices;}else if(action=="rename")Store.desks.Find(v=>v.id==Store.active).name=CleanName(value);else if(action=="delete"){if(Store.desks.Count<=1)return;var id=Store.active;Profile("switch",Store.desks.First(v=>v.id!=id).id);Store.desks.RemoveAll(v=>v.id==id);}else return;Normalize();EnsureSource();Reset();Publish();}
 static string CleanName(string value){value=(value??"").Trim();return value.Length==0?"New desk":value.Substring(0,Math.Min(32,value.Length));}
 void EnsureSource(){if(!Devices.Any(d=>d.id==Source&&d.Available&&d.kind=="Windows"))Source=Devices.Where(d=>d.Available&&d.kind=="Windows").Select(d=>d.id).FirstOrDefault()??"";}
 public void SleepDevice(string id,bool sleeping){if(!Connected)return;if(!network.IsHost){network.Send(new{t="sleep",id=id,sleeping=sleeping});return;}var d=Devices.Find(v=>v.id==id);if(d==null)return;Reset();d.sleeping=sleeping;EnsureSource();Publish();}
 public void ResizeDevice(string id,double scale){if(!Connected||Double.IsNaN(scale)||Double.IsInfinity(scale))return;scale=Math.Max(.25,Math.Min(3,scale));if(!network.IsHost){network.Send(new{t="scale",id=id,scale=scale});return;}var d=Devices.Find(v=>v.id==id);if(d==null)return;d.scale=scale;Normalize();Reset();Publish();}
 public void SetAwake(string id,bool awake){if(!network.IsHost){network.Send(new{t="awake",awake=awake});return;}var d=Devices.Find(v=>v.id==id);if(d==null||d.awake==awake)return;Reset();d.awake=awake;EnsureSource();Publish();}
 public void RemoveDevice(string id){if(id==Network.LocalId)return;if(!network.IsHost){pendingRemovals.Add(id);Wire.SaveSecret("pending-removals.bin",Wire.Json(pendingRemovals));Devices.RemoveAll(item=>item.id==id);Wire.SaveSecret("client-devices.bin",Wire.Json(Devices));if(Connected)network.Send(new{t="remove",id=id});if(Changed!=null)Changed();return;}if(id==Network.LocalId)return;var d=Devices.Find(v=>v.id==id);if(d==null)return;network.Forget(id);Devices.Remove(d);foreach(var p in Store.desks){p.devices.RemoveAll(v=>v.id==id);}Normalize();EnsureSource();Reset();Publish();}
 void HandlePeer(Peer p,Dictionary<string,object> m){if(p.Closed)return;string t=Wire.S(m,"t");if(t=="share"){object body;if(p.Sharing&&m.TryGetValue("body",out body)&&body is Dictionary<string,object>)ForwardShared(p.Id,Wire.S(m,"to"),(Dictionary<string,object>)body);return;}if(t=="automatic"&&p.Kind=="Windows")SetAutomatic(Wire.S(m,"enabled")=="True");if(t=="fixed-source"&&p.Kind=="Windows")UseSource(Wire.S(m,"id"));if(t=="awake")SetAwake(p.Id,Wire.S(m,"awake")=="True");if(t=="sleep")SleepDevice(Wire.S(m,"id"),Wire.S(m,"sleeping")=="True");if(t=="remove"&&p.Kind=="Windows")RemoveDevice(Wire.S(m,"id"));if(t=="scale"){double scale;if(Double.TryParse(Wire.S(m,"scale"),out scale))ResizeDevice(Wire.S(m,"id"),scale);}if(t=="profile"&&p.Kind=="Windows")Profile(Wire.S(m,"action"),Wire.S(m,"value"));if(t=="source"&&p.Kind=="Windows"&&Automatic&&Wire.S(m,"id")==p.Id)SelectSource(Wire.S(m,"id"));if(t=="layout"){double x,y;if(Double.TryParse(Wire.S(m,"x"),out x)&&Double.TryParse(Wire.S(m,"y"),out y))Position(Wire.S(m,"id"),x,y);}if(t=="route"&&p.Kind=="Windows"&&p.Id==Source&&Wire.S(m,"epoch")==Epoch.ToString()){object e;if(m.TryGetValue("event",out e)&&e is Dictionary<string,object>)Deliver(Wire.S(m,"id"),(Dictionary<string,object>)e);}if(t=="size"){var d=Devices.Find(v=>v.id==p.Id);if(d!=null&&(d.w!=p.Width||d.h!=p.Height)){d.w=p.Width;d.h=p.Height;Normalize();Reset();Publish();}}}
 void Route(string id,object message){if(!Connected||Source!=Network.LocalId)return;var m=Wire.Parse(Wire.Json(message));if(network.IsHost)Deliver(id,m);else network.Send(new{t="route",id=id,epoch=Epoch,@event=m});}
 void Deliver(string id,Dictionary<string,object> m){if(!ValidEvent(m))return;if(Wire.S(m,"t")!="leave"&&!Devices.Any(d=>d.id==id&&d.Available))return;string t=Wire.S(m,"t");if(t!="enter"&&t!="leave"&&t!="move"&&t!="key"&&t!="button"&&t!="wheel"&&t!="touchpad")return;if(id==Network.LocalId)receiver.Handle(m);else{var p=network.Snapshot().FirstOrDefault(v=>v.Id==id);if(p!=null)p.Send(m);}}
 public static bool ValidEvent(Dictionary<string,object> m){string t=Wire.S(m,"t");if(t=="enter"||t=="move"){double x,y;if(!Double.TryParse(Wire.S(m,"x"),out x)||!Double.TryParse(Wire.S(m,"y"),out y)||Double.IsNaN(x)||Double.IsNaN(y)||x<0||x>1||y<0||y>1)return false;}if(t=="enter"||t=="leave"){string edge=Wire.S(m,"edge","");return edge==""||edge=="left"||edge=="right"||edge=="top"||edge=="bottom";}if(t=="key")return Wire.I(m,"vk")>0&&Wire.I(m,"vk")<255&&Wire.I(m,"scan")>=0&&Wire.I(m,"scan")<256&&Wire.S(m,"text").Length<=32&&(Wire.S(m,"down")=="True"||Wire.S(m,"down")=="False");if(t=="button")return Wire.I(m,"button")>=1&&Wire.I(m,"button")<=3&&(Wire.S(m,"down")=="True"||Wire.S(m,"down")=="False");if(t=="touchpad")return TouchpadBridge.Valid(m);if(t=="wheel")return Math.Abs((long)Wire.I(m,"delta"))<=12000;return t=="move";}
 public void SendShared(string to,object body){if(!Connected||Preview)return;var message=Wire.Parse(Wire.Json(body));if(network.IsHost)ForwardShared(Network.LocalId,to,message);else network.Send(new{t="share",to=to,body=message});}
 void ForwardShared(string from,string to,Dictionary<string,object> body){
 var source=Devices.Find(d=>d.id==from);var targetDevice=Devices.Find(d=>d.id==to);string kind=Wire.S(body,"kind");bool mic=kind.StartsWith("mic-");
 if(source==null||targetDevice==null||!source.sharing||!targetDevice.sharing||from==to)return;
 if(!(mic?source.online&&!source.sleeping:source.Available)||!(mic?targetDevice.online&&!targetDevice.sleeping:targetDevice.Available))return;
 if(source.kind=="Android"&&!(kind=="mic-list"||kind=="mic-begin"||kind=="mic-data"||kind=="mic-stop"||kind=="mic-error"))return;
 if(targetDevice.kind=="Android"&&!(kind=="mic-list-request"||kind=="mic-request"||kind=="mic-accept"||kind=="mic-stop"))return;
 if(Wire.Json(body).Length>14000)return;if(to==Network.LocalId){if(Shared!=null)Shared(from,body);}else{var target=network.Snapshot().FirstOrDefault(p=>p.Id==to);if(target!=null)target.Send(new{t="share",from=from,body=body});}}

 public void Receive(Dictionary<string,object> m){string t=Wire.S(m,"t");if(t=="share"){object body;if(m.TryGetValue("body",out body)&&body is Dictionary<string,object>&&Shared!=null)Shared(Wire.S(m,"from"),(Dictionary<string,object>)body);return;}if(t=="desk"){Connected=true;Store.automatic=Wire.S(m,"automatic","True")=="True";Store.active=Wire.S(m,"desk");object profiles;if(m.TryGetValue("desks",out profiles))Store.desks=new JavaScriptSerializer().Deserialize<List<DeskProfile>>(Wire.Json(profiles));Source=Wire.S(m,"source");Epoch=Convert.ToInt64(m["epoch"]);Devices=new JavaScriptSerializer().Deserialize<List<Device>>(Wire.Json(m["devices"]));foreach(var id in pendingRemovals.ToArray()){if(Devices.Any(d=>d.id==id))network.Send(new{t="remove",id=id});else pendingRemovals.Remove(id);}Devices.RemoveAll(d=>pendingRemovals.Contains(d.id));Wire.SaveSecret("pending-removals.bin",Wire.Json(pendingRemovals));Wire.SaveSecret("client-devices.bin",Wire.Json(Devices));Apply();}else if(t=="offline"){Connected=false;Input.Home();Input.Enabled=false;foreach(var d in Devices)d.online=d.id==Network.LocalId;receiver.Handle(Wire.Parse("{\"t\":\"leave\"}"));if(Changed!=null)Changed();}else receiver.Handle(m);}
 public void Dispose(){Connected=false;Input.Dispose();}
}
}
