using System;
using System.Linq;
using System.Drawing;
using System.Windows.Forms;
namespace Velixa {
public partial class MainForm {
 bool mediaEnabled,mediaUpdating;string micSource=Network.LocalId,speakerSource=Network.LocalId,localMicName="",localSpeakerName="";SpeakerShare speakers;Timer mediaTimer;DateTime mediaRetry=DateTime.MinValue;
 void StartMedia(){mediaEnabled=Wire.LoadSecret("media-enabled.bin","false")=="true";micSource=Wire.LoadSecret("media-mic-source.bin",Network.LocalId);speakerSource=Wire.LoadSecret("media-speaker-source.bin",Network.LocalId);localMicName=Wire.LoadSecret("media-local-mic.bin","");localSpeakerName=Wire.LoadSecret("media-local-speaker.bin","");microphone.PreferredInputName=localMicName;microphone.AllowRemoteRequests=mediaEnabled;microphone.ReceiveEnabled=mediaEnabled;speakers=new SpeakerShare((to,body)=>session.SendShared(to,body),Ui,()=>session,()=>mediaEnabled,()=>localSpeakerName);speakers.Changed=ReconcileMedia;mediaTimer=new Timer{Interval=2000};mediaTimer.Tick+=(s,e)=>ReconcileMedia();mediaTimer.Start();if(!session.Preview)AudioEndpoints.RecoverAndHide();}
 void SetMediaEnabled(bool enabled){mediaEnabled=enabled;Wire.SaveSecret("media-enabled.bin",enabled?"true":"false");if(!enabled){microphone.AllowRemoteRequests=false;microphone.ReceiveEnabled=false;microphone.StopReceiving();microphone.StopSending();speakers.Stop();AudioEndpoints.RestoreAndHide();}ReconcileMedia();RefreshMediaControls();if(sharingPanel!=null&&sharingPanel.Tag is Action)((Action)sharingPanel.Tag)();}
 void ReconcileMedia(){if(mediaUpdating||session==null||microphone==null)return;mediaUpdating=true;try{string preferredMic=localMicName==""?AudioEndpoints.LocalDefaultName(true):localMicName;if(microphone.PreferredInputName!=preferredMic){microphone.PreferredInputName=preferredMic;microphone.StopSending();}session.MediaSettings(mediaEnabled,micSource,speakerSource);var local=session.Devices.Find(d=>d.id==Network.LocalId);bool live=mediaEnabled&&session.Connected&&local!=null&&local.Available;microphone.AllowRemoteRequests=live;microphone.ReceiveEnabled=live;if(!live){microphone.StopReceiving();microphone.StopSending();speakers.Stop();AudioEndpoints.RestoreAndHide();return;}bool remote=micSource!=Network.LocalId&&micSource!="";string destination=session.SpeakerTarget(Network.LocalId);bool remoteSpeaker=destination!=""&&destination!=Network.LocalId;bool remoteMic=remote&&session.Devices.Any(d=>d.id==micSource&&d.Available&&(d.media||d.kind=="Android"));if(remoteMic){AudioEndpoints.EnableCable();if(!microphone.Receiving&&!microphone.Pending&&DateTime.UtcNow>=mediaRetry){mediaRetry=DateTime.UtcNow.AddSeconds(10);microphone.OutputName="";microphone.OutputDevice=-1;microphone.RequestRemoteMic(micSource,-2);}if(microphone.Receiving)AudioEndpoints.UseCableMicrophone();else AudioEndpoints.RestoreMicrophone();}else{if(microphone.Receiving||microphone.Pending)microphone.StopReceiving();AudioEndpoints.RestoreMicrophone();}AudioEndpoints.RestoreSpeaker();if(!remoteMic)AudioEndpoints.HideCable();speakers.Reconcile();if(remoteSpeaker&&speakers.Ready)AudioEndpoints.SuppressLocalSpeakers();else AudioEndpoints.RestoreLocalSpeakers();if(mediaState!=null)mediaState.Text=remoteSpeaker?(speakers.Ready?"System audio redirected to "+PeerLabel(destination)+".":"Waiting for "+PeerLabel(destination)+" speaker; playing locally."):"";RefreshMediaControls();}catch(Exception e){if(speakers!=null)speakers.Stop();AudioEndpoints.RestoreAndHide();if(mediaState!=null&&!mediaState.IsDisposed)mediaState.Text=e.Message;status.Text="Media sharing: "+e.Message;}finally{mediaUpdating=false;}}
 string PeerLabel(string id){var d=session.Devices.Find(v=>v.id==id);return id==Network.LocalId?"This PC":d==null?"Unavailable device":d.name;}
 void RefreshMediaControls(){if(mediaToggle==null||mediaToggle.IsDisposed)return;mediaToggle.Checked=mediaEnabled;mediaToggle.Enabled=microphone!=null;mediaToggle.Invalidate();mediaMic.Visible=mediaSpeaker.Visible=mediaEnabled;mediaState.Visible=false;mediaMic.Text="Mic: "+PeerLabel(micSource)+" ▾";mediaSpeaker.Text="Speaker: "+PeerLabel(speakerSource)+" ▾";bool micHere=micSource==Network.LocalId||session.Devices.Any(d=>d.media&&d.micSource==Network.LocalId);bool speakerHere=speakerSource==Network.LocalId||session.Devices.Any(d=>d.media&&session.SpeakerTarget(d.id)==Network.LocalId);localMic.Enabled=mediaEnabled&&micHere;localSpeaker.Enabled=mediaEnabled&&speakerHere;localMic.Text=localMic.Enabled?"My mic: "+(localMicName==""?"Default ▾":localMicName):"Using "+PeerLabel(micSource)+" microphone";localSpeaker.Text=localSpeaker.Enabled?"My speaker: "+(localSpeakerName==""?"Default ▾":localSpeakerName):"Using "+PeerLabel(speakerSource)+" speaker";if(!mediaEnabled){localMic.Text="My microphone · local";localSpeaker.Text="My speaker · local";}if(mediaState.Text=="")mediaState.Text=mediaEnabled?"Choose microphone and speaker independently.":"";if(micLabel!=null)micLabel.Text=mediaEnabled?(microphone==null?"":microphone.State):"Using this PC’s own audio devices.";}
 void MediaSourceMenu(bool input){var menu=DarkMenu.Create();foreach(var d in session.Devices.Where(d=>input||d.kind=="Windows")){string id=d.id;bool ready=id==Network.LocalId||(d.Available&&(d.media||input&&d.kind=="Android"));var item=new ToolStripMenuItem(d.name+(id==Network.LocalId?" · This PC":"")+(ready?"":!d.Available?" · Offline":" · Enable media sharing there")){Enabled=ready,Checked=(input?micSource:speakerSource)==id};item.Click+=(s,e)=>{if(input){micSource=id;microphone.StopReceiving();mediaRetry=DateTime.MinValue;}else{speakerSource=id;speakers.Stop();}Wire.SaveSecret(input?"media-mic-source.bin":"media-speaker-source.bin",id);mediaState.Text="";ReconcileMedia();RefreshMediaControls();};menu.Items.Add(item);}var button=input?mediaMic:mediaSpeaker;menu.Show(button,0,button.Height);}
 void LocalMediaMenu(bool input){var menu=DarkMenu.Create();foreach(var d in WaveAudio.FullDevices(input).Where(d=>d.Name.IndexOf("CABLE",StringComparison.OrdinalIgnoreCase)<0)){string name=d.Name;var item=new ToolStripMenuItem(name){Checked=name==(input?localMicName:localSpeakerName)};item.Click+=(s,e)=>{if(input){localMicName=name;microphone.PreferredInputName=name;microphone.StopSending();if(micSource==Network.LocalId)AudioEndpoints.SetHardware(true,name);}else{localSpeakerName=name;speakers.Stop();if(speakerSource==Network.LocalId)AudioEndpoints.SetHardware(false,name);}Wire.SaveSecret(input?"media-local-mic.bin":"media-local-speaker.bin",name);RefreshMediaControls();};menu.Items.Add(item);}if(menu.Items.Count==0)menu.Items.Add("No physical audio devices available").Enabled=false;var button=input?localMic:localSpeaker;menu.Show(button,0,button.Height);}
}
}



