using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Drawing;
using System.Drawing.Imaging;
using System.Collections.Generic;
using System.Collections.Concurrent;
using System.Security.Cryptography;
using System.Threading;
using System.Threading.Tasks;
using System.Runtime.InteropServices;
using System.Windows.Forms;
namespace Velixa {
public sealed class TransferStatus {
 public string Id,Name,Peer,Message,Path;public long Done,Total;public bool Finished,Failed;public readonly CancellationTokenSource Cancel=new CancellationTokenSource();public readonly System.Diagnostics.Stopwatch Clock=System.Diagnostics.Stopwatch.StartNew();
}
public sealed class ShareService:IDisposable {
 public const int ChunkSize=8192;public const long MaxFile=100L*1024*1024*1024,MaxClipboard=16*1024*1024;
 readonly Action<string,object> send;readonly Action<Action> ui;readonly Func<string[]> targets;readonly string folder;
 readonly ConcurrentDictionary<string,TaskCompletionSource<Dictionary<string,object>>> replies=new ConcurrentDictionary<string,TaskCompletionSource<Dictionary<string,object>>>();
 readonly ConcurrentDictionary<string,BlockingCollection<Dictionary<string,object>>> incoming=new ConcurrentDictionary<string,BlockingCollection<Dictionary<string,object>>>();
 readonly ConcurrentDictionary<string,TransferStatus> jobs=new ConcurrentDictionary<string,TransferStatus>();
 readonly SemaphoreSlim outgoing=new SemaphoreSlim(1);readonly System.Windows.Forms.Timer clipboardTimer;uint sequence;bool disposed;public bool ClipboardEnabled=true,FilesEnabled=true;bool clipboardSending;
 public Action<TransferStatus> Progress;public Action<string,string> ReceivedFile;public Action<string,byte[]> ReceivedClipboard;public Action<string,Dictionary<string,object>> AudioMessage;
 [DllImport("user32.dll")]static extern uint GetClipboardSequenceNumber();
 public ShareService(Action<string,object> transport,Action<Action> dispatch,Func<string[]> destinations,string receiveFolder=null,bool watchClipboard=true){send=transport;ui=dispatch;targets=destinations;folder=receiveFolder??System.IO.Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),"Downloads","Velixa");if(watchClipboard){sequence=GetClipboardSequenceNumber();clipboardTimer=new System.Windows.Forms.Timer{Interval=650};clipboardTimer.Tick+=(s,e)=>ClipboardChanged();clipboardTimer.Start();}}
 public static bool SafeName(string name){return !String.IsNullOrWhiteSpace(name)&&name.Length<=180&&name==System.IO.Path.GetFileName(name)&&name.IndexOfAny(System.IO.Path.GetInvalidFileNameChars())<0&&!name.EndsWith(".")&&!name.EndsWith(" ")&&!new[]{"CON","PRN","AUX","NUL","COM1","COM2","COM3","COM4","COM5","COM6","COM7","COM8","COM9","LPT1","LPT2","LPT3","LPT4","LPT5","LPT6","LPT7","LPT8","LPT9"}.Contains(System.IO.Path.GetFileNameWithoutExtension(name).ToUpperInvariant());}
 void Emit(string peer,object body){if(!disposed)ui(()=>{if(!disposed)send(peer,body);});}
 void Notify(TransferStatus status){if(Progress!=null)ui(()=>{if(!disposed&&Progress!=null)Progress(status);});}
 public void Handle(string from,Dictionary<string,object> m){string kind=Wire.S(m,"kind"),id=Wire.S(m,"id"),key=from+"/"+id;Guid guid;if(!Guid.TryParseExact(id,"N",out guid)&&!kind.StartsWith("mic-"))return;if(kind.StartsWith("mic-")){if(AudioMessage!=null)AudioMessage(from,m);return;}if(kind=="ack"||kind=="error"){TaskCompletionSource<Dictionary<string,object>> waiting;if(replies.TryGetValue(key,out waiting))waiting.TrySetResult(m);return;}if(kind=="begin"){
  long size;string name=Wire.S(m,"name"),format=Wire.S(m,"format");bool clip=format=="text"||format=="png";
  if(disposed||incoming.Count>=4||(!clip&&!FilesEnabled)||(clip&&!ClipboardEnabled)||!SafeName(name)||!Int64.TryParse(Wire.S(m,"size"),out size)||size<0||size>(clip?MaxClipboard:MaxFile)||(format!="file"&&!clip)){Emit(from,new{kind="error",id=id,message="Transfer is unavailable or too large"});return;}
  var queue=new BlockingCollection<Dictionary<string,object>>(8);if(!incoming.TryAdd(key,queue)){queue.Dispose();return;}var job=new TransferStatus{Id=id,Name=name,Peer=from,Total=size,Message=clip?"Receiving clipboard":"Receiving"};jobs[key]=job;Task.Run(()=>Receive(from,id,name,size,format,queue,job,key));return;
 }BlockingCollection<Dictionary<string,object>> pending;if(incoming.TryGetValue(key,out pending)){if(!pending.TryAdd(m)){TransferStatus job;if(jobs.TryGetValue(key,out job))job.Cancel.Cancel();}}}
 Dictionary<string,object> Request(string peer,string id,object message,CancellationToken cancel){var key=peer+"/"+id;var tcs=new TaskCompletionSource<Dictionary<string,object>>();replies[key]=tcs;try{Emit(peer,message);if(!tcs.Task.Wait(15000,cancel))throw new IOException("Device did not respond");var result=tcs.Task.Result;if(Wire.S(result,"kind")=="error")throw new IOException(Wire.S(result,"message","Transfer failed"));return result;}finally{TaskCompletionSource<Dictionary<string,object>> old;replies.TryRemove(key,out old);}}
 public Task SendFiles(string peer,string[] paths){return Task.Run(()=>{foreach(string path in paths){if(disposed)return;if(!File.Exists(path)){var failed=new TransferStatus{Id=Guid.NewGuid().ToString("N"),Name=System.IO.Path.GetFileName(path),Peer=peer,Finished=true,Failed=true,Message="Drop files; folders are not supported"};Notify(failed);continue;}SendStream(peer,System.IO.Path.GetFileName(path),"file",()=>new FileStream(path,FileMode.Open,FileAccess.Read,FileShare.Read));}});}
 public Task SendClipboard(string peer,string format,byte[] bytes){return Task.Run(()=>SendStream(peer,format=="png"?"Clipboard.png":"Clipboard.txt",format,()=>new MemoryStream(bytes,false)));}
 void SendStream(string peer,string name,string format,Func<Stream> open){string id=Guid.NewGuid().ToString("N"),key=peer+"/"+id;var job=new TransferStatus{Id=id,Name=name,Peer=peer,Message=format=="file"?"Sending":"Sharing clipboard"};jobs[key]=job;bool acquired=false;try{outgoing.Wait(job.Cancel.Token);acquired=true;if(disposed)throw new OperationCanceledException();using(var stream=open())using(var hash=SHA256.Create()){job.Total=stream.Length;if(!SafeName(name)||job.Total>(format=="file"?MaxFile:MaxClipboard))throw new IOException("Item exceeds the sharing limit");Notify(job);Request(peer,id,new{kind="begin",id=id,name=name,size=job.Total,format=format},job.Cancel.Token);var buffer=new byte[ChunkSize];long offset=0;long lastUpdate=0;int read;while((read=stream.Read(buffer,0,buffer.Length))>0){job.Cancel.Token.ThrowIfCancellationRequested();hash.TransformBlock(buffer,0,read,buffer,0);var reply=Request(peer,id,new{kind="chunk",id=id,offset=offset,data=Convert.ToBase64String(buffer,0,read)},job.Cancel.Token);offset+=read;if(Wire.S(reply,"offset")!=offset.ToString())throw new IOException("Transfer acknowledgement is out of order");job.Done=offset;if(job.Clock.ElapsedMilliseconds-lastUpdate>100){Notify(job);lastUpdate=job.Clock.ElapsedMilliseconds;}}hash.TransformFinalBlock(new byte[0],0,0);Request(peer,id,new{kind="end",id=id,hash=Wire.Hex(hash.Hash)},job.Cancel.Token);job.Finished=true;job.Message="Sent";Notify(job);}}catch(Exception e){job.Failed=true;job.Finished=true;job.Message=e is OperationCanceledException?"Canceled":e.Message;Emit(peer,new{kind="cancel",id=id});Notify(job);}finally{TransferStatus old;jobs.TryRemove(key,out old);if(acquired)outgoing.Release();}}
 void Receive(string from,string id,string name,long size,string format,BlockingCollection<Dictionary<string,object>> queue,TransferStatus job,string key){string temp=null;try{Directory.CreateDirectory(folder);if((File.GetAttributes(folder)&FileAttributes.ReparsePoint)!=0)throw new IOException("Choose a regular receive folder");temp=System.IO.Path.Combine(folder,".velixa-"+id+".partial");using(var file=new FileStream(temp,FileMode.CreateNew,FileAccess.Write,FileShare.None))using(var hash=SHA256.Create()){Emit(from,new{kind="ack",id=id,offset=0});long offset=0,lastUpdate=0;for(;;){Dictionary<string,object> m;if(!queue.TryTake(out m,15000,job.Cancel.Token))throw new IOException("Transfer timed out");string kind=Wire.S(m,"kind");if(kind=="cancel")throw new OperationCanceledException();if(kind=="chunk"){long at;string data=Wire.S(m,"data");if(data.Length>11000||!Int64.TryParse(Wire.S(m,"offset"),out at)||at!=offset)throw new IOException("Invalid transfer sequence");var bytes=Convert.FromBase64String(data);if(bytes.Length==0||bytes.Length>ChunkSize||offset+bytes.Length>size)throw new IOException("Invalid transfer size");file.Write(bytes,0,bytes.Length);hash.TransformBlock(bytes,0,bytes.Length,bytes,0);offset+=bytes.Length;job.Done=offset;Emit(from,new{kind="ack",id=id,offset=offset});if(job.Clock.ElapsedMilliseconds-lastUpdate>100){Notify(job);lastUpdate=job.Clock.ElapsedMilliseconds;}continue;}if(kind!="end")throw new IOException("Invalid transfer message");hash.TransformFinalBlock(new byte[0],0,0);if(offset!=size||!Wire.Equal(Wire.S(m,"hash"),Wire.Hex(hash.Hash)))throw new IOException("File verification failed");file.Flush(true);break;}}
  if(format=="file"){string dest=UniquePath(folder,name);File.Move(temp,dest);temp=null;job.Path=dest;ui(()=>{if(!disposed&&ReceivedFile!=null)ReceivedFile(from,dest);});}else{var bytes=File.ReadAllBytes(temp);if(format=="png"&&!ValidPng(bytes))throw new IOException("Clipboard image dimensions are too large or invalid");File.Delete(temp);temp=null;ui(()=>{if(disposed||!ClipboardEnabled)return;if(ReceivedClipboard!=null)ReceivedClipboard(format,bytes);else ApplyClipboard(format,bytes);});}job.Finished=true;job.Message=format=="file"?"Received · saved to Downloads / Velixa":"Clipboard shared";Emit(from,new{kind="ack",id=id,offset=size});Notify(job);
 }catch(Exception e){if(temp!=null)try{File.Delete(temp);temp=null;}catch{}job.Failed=true;job.Finished=true;job.Message=e is OperationCanceledException?"Canceled":e.Message;Emit(from,new{kind="error",id=id,message=job.Message});Notify(job);}finally{if(temp!=null)try{File.Delete(temp);}catch{}BlockingCollection<Dictionary<string,object>> old;incoming.TryRemove(key,out old);TransferStatus status;jobs.TryRemove(key,out status);}}
 public static string UniquePath(string folder,string name){if(!SafeName(name))throw new IOException("Invalid filename");string path=System.IO.Path.Combine(folder,name);for(int i=1;File.Exists(path)||Directory.Exists(path);i++)path=System.IO.Path.Combine(folder,System.IO.Path.GetFileNameWithoutExtension(name)+" ("+i+")"+System.IO.Path.GetExtension(name));return path;}
 void ClipboardChanged(){uint current=GetClipboardSequenceNumber();if(disposed||!ClipboardEnabled||clipboardSending||current==sequence)return;sequence=current;string[] peers=targets();if(peers.Length==0)return;try{byte[] bytes=null;string format="";if(Clipboard.ContainsText()){format="text";bytes=Encoding.UTF8.GetBytes(Clipboard.GetText());}else if(Clipboard.ContainsImage()){using(var image=Clipboard.GetImage())using(var stream=new MemoryStream()){if(image==null||image.Width>8192||image.Height>8192)return;image.Save(stream,ImageFormat.Png);format="png";bytes=stream.ToArray();}}if(bytes==null||bytes.LongLength>MaxClipboard)return;clipboardSending=true;var captured=bytes;var type=format;Task.Run(async()=>{try{foreach(string peer in peers)await SendClipboard(peer,type,captured);}finally{ui(()=>clipboardSending=false);}});}catch(ExternalException){sequence=0;}}
 public static bool ValidPng(byte[] bytes){if(bytes==null||bytes.Length<24||!bytes.Take(8).SequenceEqual(new byte[]{137,80,78,71,13,10,26,10}))return false;long width=((long)bytes[16]<<24)|((long)bytes[17]<<16)|((long)bytes[18]<<8)|bytes[19],height=((long)bytes[20]<<24)|((long)bytes[21]<<16)|((long)bytes[22]<<8)|bytes[23];return width>0&&height>0&&width<=8192&&height<=8192&&width*height<=16000000;}
 void ApplyClipboard(string format,byte[] bytes){try{if(format=="text")Clipboard.SetText(Encoding.UTF8.GetString(bytes));else if(ValidPng(bytes))using(var stream=new MemoryStream(bytes))using(var image=Image.FromStream(stream)){if(image.Width>8192||image.Height>8192)return;Clipboard.SetImage(image);}sequence=GetClipboardSequenceNumber();}catch(ExternalException){}catch(ArgumentException){}}
 public void CancelAll(){foreach(var job in jobs.Values)job.Cancel.Cancel();}
 public void Dispose(){disposed=true;if(clipboardTimer!=null)clipboardTimer.Dispose();CancelAll();foreach(var reply in replies.Values)reply.TrySetCanceled();}
}
}
