using System;
using System.IO;
using System.Threading;
using NAudio.Wave;
using NAudio.CoreAudioApi;
using Velixa;
public static class AudioLoopbackRegression {
 sealed class Tone:WaveProvider16 {readonly double frequency;int sample;public Tone(double hz):base(48000,2){frequency=hz;}public override int Read(short[] buffer,int offset,int count){for(int i=0;i<count;i+=2){short value=(short)(Math.Sin(2*Math.PI*frequency*sample++/48000)*3000);buffer[offset+i]=buffer[offset+i+1]=value;}return count;}}
 static WaveOutEvent Play(double hz){var player=new WaveOutEvent{DesiredLatency=80};player.Init(new Tone(hz));player.Play();return player;}
 public static void Main(string[] args){try{if(args[0]=="tone"){DateTime end=DateTime.UtcNow.AddSeconds(20);while(!File.Exists(args[1])&&DateTime.UtcNow<end)Thread.Sleep(25);if(!File.Exists(args[1]))throw new Exception("Capture did not signal readiness");using(var tone=Play(997))Thread.Sleep(6000);return;}using(var enumerator=new MMDeviceEnumerator())using(var output=enumerator.GetDefaultAudioEndpoint(DataFlow.Render,Role.Multimedia)){bool muted=output.AudioEndpointVolume.Mute;try{output.AudioEndpointVolume.Mute=true;double sin997=0,cos997=0,sin733=0,cos733=0;long samples=0;object gate=new object();using(var own=Play(733))using(var capture=new ProcessAudio(bytes=>{lock(gate){for(int i=0;i<bytes.Length;i+=4){double value=BitConverter.ToInt16(bytes,i);double phase=2*Math.PI*samples/48000;sin997+=value*Math.Sin(phase*997);cos997+=value*Math.Cos(phase*997);sin733+=value*Math.Sin(phase*733);cos733+=value*Math.Cos(phase*733);samples++;}}})){File.WriteAllText(args[1],"ready");Thread.Sleep(5000);capture.Check();}double remote=2*Math.Sqrt(sin997*sin997+cos997*cos997)/Math.Max(1,samples),ownLevel=2*Math.Sqrt(sin733*sin733+cos733*cos733)/Math.Max(1,samples);Console.WriteLine("Frames="+samples+" external997Hz="+remote.ToString("F2")+" excluded733Hz="+ownLevel.ToString("F2"));if(samples<48000||remote<100)throw new Exception("External application audio was not captured while endpoint muted");if(ownLevel>remote*.05)throw new Exception("Velixa process audio leaked into system capture");Console.WriteLine("PASS external application audio survives endpoint mute");Console.WriteLine("PASS local microphone playback process excluded from speaker capture");}finally{output.AudioEndpointVolume.Mute=muted;}if(output.AudioEndpointVolume.Mute!=muted)throw new Exception("Mute state was not restored");Console.WriteLine("PASS original endpoint mute state restored");}}catch(Exception e){Console.Error.WriteLine(e);Environment.ExitCode=1;}}
}
