using System;
using System.Drawing;
using System.Linq;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Threading.Tasks;
using System.Windows.Forms;
using Velixa;
public static class CaptionClickRegression {
 [DllImport("user32.dll")]static extern IntPtr SendMessage(IntPtr h,int m,IntPtr w,IntPtr l);
 [DllImport("user32.dll")]static extern IntPtr WindowFromPoint(Point point);
 [DllImport("user32.dll")]static extern IntPtr GetAncestor(IntPtr h,uint flag);
 [StructLayout(LayoutKind.Sequential)]struct Title {public uint size;public Native.RECT bar;[MarshalAs(UnmanagedType.ByValArray,SizeConst=6)]public uint[] state;[MarshalAs(UnmanagedType.ByValArray,SizeConst=6)]public Native.RECT[] rects;}
 static object Field(object o,string n){return o.GetType().GetField(n,BindingFlags.NonPublic|BindingFlags.Instance).GetValue(o);}
 [STAThread]static void Main(){try{Native.SetProcessDpiAwarenessContext(new IntPtr(-4));}catch{}Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);Exception failure=null;int cycles=0;Point original=Cursor.Position;using(var form=new MainForm(new[]{"--preview-desk"}){Opacity=.01,TopMost=true,ShowInTaskbar=false}){form.Shown+=(s,e)=>form.BeginInvoke((Action)(async()=>{try{var desk=(DeskSession)Field(form,"session");var receiver=(Receiver)Field(form,"receiver");for(int i=0;i<32&&cycles<8;i++){form.Show();form.Activate();await Task.Delay(80);int size=Marshal.SizeOf(typeof(Title));IntPtr pointer=Marshal.AllocHGlobal(size);Title title;try{Marshal.StructureToPtr(new Title{size=(uint)size,state=new uint[6],rects=new Native.RECT[6]},pointer,false);SendMessage(form.Handle,0x33f,IntPtr.Zero,pointer);title=(Title)Marshal.PtrToStructure(pointer,typeof(Title));}finally{Marshal.FreeHGlobal(pointer);}var r=title.rects[cycles%2==0?2:5];if(r.Right<=r.Left||r.Bottom<=r.Top)throw new Exception("Title button geometry unavailable");var point=new Point((r.Left+r.Right)/2,(r.Top+r.Bottom)/2);if(GetAncestor(WindowFromPoint(point),2)!=form.Handle)throw new Exception("Test title button is not topmost; no click sent");var bounds=SystemInformation.VirtualScreen;receiver.Handle(Wire.Parse(Wire.Json(new{t="enter",edge="top",x=(point.X-bounds.Left)/(double)(bounds.Width-1),y=(point.Y-bounds.Top)/(double)(bounds.Height-1)})));await Task.Delay(150);if(Math.Abs(Cursor.Position.X-point.X)>3||Math.Abs(Cursor.Position.Y-point.Y)>3){receiver.Handle(Wire.Parse("{\"t\":\"leave\"}"));continue;}await Task.Run(()=>{receiver.Handle(Wire.Parse("{\"t\":\"button\",\"button\":1,\"down\":true}"));System.Threading.Thread.Sleep(40);receiver.Handle(Wire.Parse("{\"t\":\"button\",\"button\":1,\"down\":false}"));});var end=DateTime.UtcNow.AddSeconds(2);while(form.Visible&&DateTime.UtcNow<end)await Task.Delay(20);if(form.Visible&&(Math.Abs(Cursor.Position.X-point.X)>5||Math.Abs(Cursor.Position.Y-point.Y)>5)){receiver.Handle(Wire.Parse("{\"t\":\"leave\"}"));continue;}if(form.Visible||form.IsDisposed||!desk.Connected)throw new Exception("Caption click did not hide a live session; cursor="+Cursor.Position+" visible="+form.Visible+" disposed="+form.IsDisposed+" connected="+desk.Connected);receiver.Handle(Wire.Parse("{\"t\":\"leave\"}"));cycles++;}if(cycles!=8)throw new Exception("Physical pointer activity interrupted title-bar test; rerun when idle");}catch(Exception ex){failure=ex;}finally{Native.Mouse(4);Native.Position(original.X,original.Y);form.GetType().GetField("closing",BindingFlags.NonPublic|BindingFlags.Instance).SetValue(form,true);form.Close();}}));Application.Run(form);}if(failure!=null){Console.Error.WriteLine(failure);Environment.ExitCode=1;}else Console.WriteLine(cycles+" actual injected title-bar clicks passed (minimize and close); receiver and session remain alive.");}
}
