using System;
using System.IO;
using System.Linq;
using System.Drawing;
using System.Reflection;
using System.Windows.Forms;
using System.Collections.Generic;
using System.Collections.Concurrent;
using System.Threading;
using Velixa;
public static class DesktopQA {
 static int checks;static void Check(bool ok,string name){if(!ok)throw new Exception(name);checks++;Console.WriteLine("PASS "+name);}
 static object Get(object o,string name){return o.GetType().GetField(name,BindingFlags.NonPublic|BindingFlags.Instance).GetValue(o);}
 static void Call(object o,string name,params object[] args){o.GetType().GetMethod(name,BindingFlags.NonPublic|BindingFlags.Instance).Invoke(o,args);}
 [STAThread]static void Main(){try{Native.SetProcessDpiAwarenessContext(new IntPtr(-4));}catch{}try{Run();Console.WriteLine(checks+" desktop QA checks passed");}catch(Exception e){Console.Error.WriteLine(e);Environment.ExitCode=1;}}
 static IEnumerable<Control> All(Control p){foreach(Control c in p.Controls){yield return c;foreach(var child in All(c))yield return child;}}
 static void Run(){
 Check(Wire.Port!=37128&&Wire.DiscoveryPort!=37129,"QA ports differ from production");string path=Wire.DataDir;Environment.SetEnvironmentVariable("VELIXA_TEST_DATA",null);bool blocked=false;try{var denied=Wire.DataDir;}catch(InvalidOperationException){blocked=true;}finally{Environment.SetEnvironmentVariable("VELIXA_TEST_DATA",path);}Check(blocked,"missing QA storage fails closed");
 using(var n=new Network()){n.IsHost=true;using(var receiver=new Receiver())using(var d=new DeskSession(n,receiver,a=>a())){d.Host();d.Input.Enabled=false;var peer=new Peer{Id=Guid.NewGuid().ToString(),Name="QA temporary device",Kind="Windows",SendAction=o=>{}};n.Peers.Add(peer);n.Joined(peer);d.Input.Enabled=false;d.ResizeDevice(Network.LocalId,.5);var local=d.Devices.First(v=>v.id==Network.LocalId);var remote=d.Devices.First(v=>v.id==peer.Id);double lo,hi;Check(new[]{"left","right","top","bottom"}.Any(side=>DeskGeometry.Segment(local.Bounds,remote.Bounds,side,out lo,out hi)),"resizing keeps screens connected at an edge");string first=d.Store.active;d.Profile("create","Second");string second=d.Store.active;d.Profile("switch",first);Check(d.Store.active==first,"switch back to original desk");d.RemoveDevice(peer.Id);Check(!d.Devices.Any(v=>v.id==peer.Id)&&d.Store.desks.All(p=>p.devices.All(v=>v.id!=peer.Id)),"forget connected device removes every saved copy");d.Profile("switch",second);Check(!d.Devices.Any(v=>v.id==peer.Id),"switching desks cannot resurrect forgotten device");var phone=new Peer{Id=Guid.NewGuid().ToString(),Name="QA Android",Kind="Android",Sharing=true,SendAction=o=>{}};n.Peers.Add(phone);n.Joined(phone);string routed=null;d.Shared=(from,body)=>routed=Wire.S(body,"kind");n.Packet(phone,Wire.Parse(Wire.Json(new{t="share",to=Network.LocalId,body=new{kind="mic-data"}})));Check(routed=="mic-data","Android can send microphone audio to PC");routed=null;n.Packet(phone,Wire.Parse(Wire.Json(new{t="share",to=Network.LocalId,body=new{kind="begin"}})));Check(routed==null,"Android cannot originate file-sharing messages");d.Input.Enabled=false;
d.Profile("rename","Renamed");Check(d.DeskName=="Renamed","rename changes active desk");d.Profile("delete","");Check(d.Store.active==first&&d.Store.desks.Count==1,"deleting active desk retains valid selection");d.Input.Enabled=false;}}
 var outgoing=new List<object>();using(var mic=new MicrophoneShare((p,o)=>outgoing.Add(o),a=>a(),id=>true)){
 mic.Handle("peer",Wire.Parse(Wire.Json(new{kind="mic-list",id=Guid.NewGuid().ToString("N"),peerName="Motorola",mics=new[]{new{id=2,name="System microphone"}}})));Check(mic.RemoteMics["peer"].Count==1,"microphone list parses wire arrays");Check(outgoing.Count==0,"microphone discovery response does not echo");mic.Handle("peer",Wire.Parse(Wire.Json(new{kind="mic-request",id=Guid.NewGuid().ToString("N"),devId=0})));Check(!mic.Sending,"remote capture requires source permission");}
 var inputs=WaveAudio.Devices(true);if(inputs.Length>0){var queue=new ConcurrentQueue<Action>();var counts=new Dictionary<string,int>{{"one",0},{"two",0},{"three",0}};MicrophoneShare mic=null;mic=new MicrophoneShare((peer,o)=>{var m=Wire.Parse(Wire.Json(o));if(Wire.S(m,"kind")=="mic-begin")mic.Handle(peer,Wire.Parse(Wire.Json(new{kind="mic-accept",id=Wire.S(m,"id"),ok=true})));if(Wire.S(m,"kind")=="mic-data")counts[peer]++;},a=>queue.Enqueue(a),id=>true);using(mic){mic.StartMany(counts.Keys.ToArray(),inputs[0].Id);DateTime until=DateTime.UtcNow.AddSeconds(5);Action action;while(DateTime.UtcNow<until&&counts.Values.Min()<8){while(queue.TryDequeue(out action))action();Thread.Sleep(10);}Check(counts.Values.All(v=>v>=8),"one microphone reaches three PCs simultaneously");mic.StopSending();}}
 Application.EnableVisualStyles();using(var f=new MainForm(new[]{"--preview-desk"}){Opacity=0,ShowInTaskbar=false}){f.Show();Application.DoEvents();var canvas=(DeskCanvas)Get(f,"desk");var session=(DeskSession)Get(f,"session");session.Devices[1].name="Motorola";
 foreach(var size in new[]{new Size(1642,920),new Size(1440,820),new Size(1200,850),new Size(920,690)}){
 f.ClientSize=size;f.PerformLayout();Application.DoEvents();using(var bmp=new Bitmap(f.Width,f.Height)){f.DrawToBitmap(bmp,new Rectangle(0,0,bmp.Width,bmp.Height));bmp.Save("build/qa-layout-"+size.Width+".png");}
 var actions=new[]{(Control)Get(f,"sourceButton"),(Control)Get(f,"micButton"),(Control)Get(f,"localSpeaker"),All(f).First(c=>c.Name=="AddDevice")};
 Check(actions.All(c=>c.Width>=36&&c.Height>=36&&c.Left>=0&&c.Right<=c.Parent.ClientSize.Width),"actions fit their panels at "+size.Width);
 Check(((Control)Get(f,"deskButton")).Text=="Switch desk","desk switch keeps its discoverable label after refresh");var headerActions=new[]{All(f).First(c=>c.Name=="AddDevice"),(Control)Get(f,"deskButton"),All(f).First(c=>c.Name=="LeaveDesk")};
 Check(headerActions.All(button=>button.Parent.Controls.OfType<Label>().All(label=>!label.Bounds.IntersectsWith(button.Bounds))),"header labels cannot cover action buttons at "+size.Width);
 Check(canvas.Width>=300&&canvas.Height>=270,"arrangement remains usable at "+size.Width);
 Check(canvas.Bounds.IntersectsWith(((Control)Get(f,"deskButton")).Bounds)==false,"arrangement does not overlap header actions at "+size.Width);
 foreach(var d in session.Devices){var card=canvas.Card(d);Check(card.Left>=0&&card.Right<=canvas.Width&&card.Top>=0&&card.Bottom<=canvas.Height,"device stays inside fitted canvas: "+d.name);}
 Check(canvas.FindDropTarget(new Point(5,5))==null,"empty canvas drops have no recipient");
 }
 canvas.Selected=session.Devices[1];canvas.SelectionChanged();Check(((Label)Get(f,"selectedName")).Text.Contains(session.Devices[1].name),"selection updates device inspector");
 Check(!All(f).Any(c=>c.Visible&&c is NavigationButton),"left navigation removed");Check(All(f).Any(c=>c.Name=="QuitApp"),"quit action lives in sidebar");
 using(var zoomRender=new Bitmap(canvas.Width,canvas.Height)){canvas.Fit();canvas.DrawToBitmap(zoomRender,canvas.ClientRectangle);float fitted=canvas.Card(session.Devices[0]).Width;canvas.Zoom(.2f);canvas.DrawToBitmap(zoomRender,canvas.ClientRectangle);Check(canvas.Card(session.Devices[0]).Width>fitted,"zoom increases device display size");canvas.Fit();canvas.DrawToBitmap(zoomRender,canvas.ClientRectangle);Check(Math.Abs(canvas.Card(session.Devices[0]).Width-fitted)<.1f,"Fit restores complete desk scale");}
 canvas.Selected=null;canvas.SelectionChanged();Check(!All(f).First(c=>c.Name=="DeviceActions").Enabled,"device actions disabled without selection");
 Call(f,"Attach");Call(f,"RefreshInspector");var share=(ShareService)Get(f,"sharing");var preferences=All(f).OfType<ToggleSwitch>().Where(c=>c.Visible).ToArray();var clipboard=preferences.First(c=>c.AccessibleName=="Clipboard sharing");bool clipBefore=share.ClipboardEnabled;typeof(Control).GetMethod("OnClick",BindingFlags.NonPublic|BindingFlags.Instance).Invoke(clipboard,new object[]{EventArgs.Empty});Check(share.ClipboardEnabled!=clipBefore&&Wire.LoadSecret("clipboard-enabled.bin","")==(share.ClipboardEnabled?"true":"false"),"inline clipboard toggle applies and persists");var files=preferences.First(c=>c.AccessibleName=="File sharing");bool filesBefore=share.FilesEnabled;typeof(Control).GetMethod("OnClick",BindingFlags.NonPublic|BindingFlags.Instance).Invoke(files,new object[]{EventArgs.Empty});Check(share.FilesEnabled!=filesBefore&&Wire.LoadSecret("files-enabled.bin","")==(share.FilesEnabled?"true":"false"),"inline file toggle applies and persists");
 Check(preferences.Length==3,"exactly three sharing switches");Check(!((Control)Get(f,"mediaMic")).Visible&&!((Control)Get(f,"mediaSpeaker")).Visible,"media off hides routing choices");
 Call(f,"SetMediaEnabled",true);Check(((Control)Get(f,"mediaMic")).Visible&&((Control)Get(f,"mediaSpeaker")).Visible,"media on reveals independent routing controls");Check(((Control)Get(f,"localMic")).Enabled&&((Control)Get(f,"localSpeaker")).Enabled,"local hardware selectors enabled for this PC sources");f.ClientSize=new Size(1440,820);Application.DoEvents();var speakerControl=(Control)Get(f,"localSpeaker");var quitControl=All(f).First(c=>c.Name=="QuitApp");Check(speakerControl.PointToScreen(new Point(0,speakerControl.Height)).Y<=quitControl.PointToScreen(Point.Empty).Y,"hardware speaker remains visible above pinned Quit at 1440x820");using(var bmp=new Bitmap(f.Width,f.Height)){f.DrawToBitmap(bmp,new Rectangle(0,0,bmp.Width,bmp.Height));bmp.Save("build/qa-media-enabled.png");}Call(f,"SetMediaEnabled",false);Check(!((MicrophoneShare)Get(f,"microphone")).AllowRemoteRequests&&!((MicrophoneShare)Get(f,"microphone")).ReceiveEnabled,"media off revokes microphone send and receive access");
 var notification=System.Runtime.InteropServices.Marshal.AllocHGlobal(24);try{for(int i=0;i<24;i++)System.Runtime.InteropServices.Marshal.WriteByte(notification,i,0);System.Runtime.InteropServices.Marshal.WriteInt32(notification,16,4);Network.LocalAwake=true;var message=Message.Create(f.Handle,0x218,new IntPtr(0x8013),notification);var args=new object[]{message};f.GetType().GetMethod("WndProc",BindingFlags.NonPublic|BindingFlags.Instance).Invoke(f,args);Check(Network.LocalAwake,"display power-off does not mark an idle PC asleep");}finally{System.Runtime.InteropServices.Marshal.FreeHGlobal(notification);}
 var collapsed=session.Devices[1];collapsed.online=false;using(var bmp=new Bitmap(canvas.Width,canvas.Height)){canvas.DrawToBitmap(bmp,canvas.ClientRectangle);var bounds=canvas.Card(collapsed);Check(Math.Min(bounds.Width,bounds.Height)<=7,"offline device is a six-pixel placeholder");canvas.Zoom(.8f);canvas.DrawToBitmap(bmp,canvas.ClientRectangle);var zoomed=canvas.Card(collapsed);Check(Math.Min(zoomed.Width,zoomed.Height)<=7,"offline strip stays thin when zoomed");canvas.Fit();canvas.DrawToBitmap(bmp,canvas.ClientRectangle);bmp.Save("build/qa-collapsed-device.png");}collapsed.online=true;
 bool quitPrompt=false;using(var cancelQuit=new System.Windows.Forms.Timer{Interval=50}){cancelQuit.Tick+=(sender,args)=>{var dialog=Application.OpenForms.Cast<Form>().FirstOrDefault(v=>v!=f&&v.Text=="Quit Velixa?");if(dialog!=null){quitPrompt=true;dialog.DialogResult=DialogResult.Cancel;cancelQuit.Stop();}};cancelQuit.Start();Call(f,"QuitApp");}Check(quitPrompt&&!f.IsDisposed,"Quit asks for confirmation and Cancel keeps the session open");
 Check(DeskCanvas.DeviceColor(Network.LocalId).R>200&&DeskCanvas.DeviceColor("remote").B>200,"local gold and remote blue colors");Get(f,"session");f.GetType().GetField("closing",BindingFlags.NonPublic|BindingFlags.Instance).SetValue(f,true);f.Close();}
 }
}
