using System;
using System.IO;
using System.Linq;
using System.Drawing;
using System.Reflection;
using System.Windows.Forms;
using Velixa;
public static class DialogRegression {
 static object Field(object o,string n){return o.GetType().GetField(n,BindingFlags.NonPublic|BindingFlags.Instance).GetValue(o);}
 [STAThread]static void Main(){try{Native.SetProcessDpiAwarenessContext(new IntPtr(-4));}catch{}Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);Exception failure=null;int renders=0;using(var f=new MainForm(new[]{"--preview-desk"}){Opacity=0,ShowInTaskbar=false})using(var timer=new Timer{Interval=100}){timer.Tick+=(s,e)=>{try{var dialog=Application.OpenForms.Cast<Form>().FirstOrDefault(v=>v!=f);if(dialog==null)return;var slider=dialog.Controls.OfType<TrackBar>().FirstOrDefault();if(slider!=null){var value=dialog.Controls.OfType<Label>().First(l=>l.Text.EndsWith("%"));if(slider.Bounds.IntersectsWith(value.Bounds))throw new Exception("Slider overlaps percentage");}using(var image=new Bitmap(dialog.Width,dialog.Height)){dialog.DrawToBitmap(image,new Rectangle(0,0,image.Width,image.Height));image.Save("build/dialog-"+renders+".png");}renders++;dialog.Close();}catch(Exception ex){failure=ex;foreach(var dialog in Application.OpenForms.Cast<Form>().Where(v=>v!=f).ToArray())dialog.Close();}};f.Shown+=(s,e)=>f.BeginInvoke((Action)(()=>{timer.Start();try{var canvas=Field(f,"desk");var desk=(DeskSession)Field(f,"session");canvas.GetType().GetMethod("SizeDialog",BindingFlags.NonPublic|BindingFlags.Instance).Invoke(canvas,new object[]{desk.Devices[0]});f.GetType().GetMethod("Attach",BindingFlags.NonPublic|BindingFlags.Instance).Invoke(f,null);f.GetType().GetMethod("MicrophoneDialog",BindingFlags.NonPublic|BindingFlags.Instance).Invoke(f,null);f.GetType().GetMethod("Settings",BindingFlags.NonPublic|BindingFlags.Instance).Invoke(f,null);using(var popup=new TransferPopup()){popup.UpdateTransfer(new TransferStatus{Id="test",Name="Holiday video.mp4",Done=347000000,Total=890000000,Message="Sending to Work laptop"});using(var bmp=new Bitmap(popup.Width,popup.Height)){popup.DrawToBitmap(bmp,new Rectangle(0,0,bmp.Width,bmp.Height));bmp.Save("build/transfer-preview.png");}}}catch(Exception ex){failure=ex;}timer.Stop();f.GetType().GetField("closing",BindingFlags.NonPublic|BindingFlags.Instance).SetValue(f,true);f.Close();}));Application.Run(f);}if(failure!=null){Console.Error.WriteLine(failure);Environment.ExitCode=1;}else Console.WriteLine(renders+" dialogs rendered; slider and value do not overlap.");}
}
