using System;
using System.IO;
using System.Linq;
using System.Drawing;
using System.Reflection;
using System.Windows.Forms;
using Velixa;
public static class FileDropRegression {
 sealed class DropProbe:Control { public static void Drop(TransferPopup panel,string[] files){var data=new DataObject(DataFormats.FileDrop,files);typeof(Control).GetMethod("OnDragDrop",BindingFlags.Instance|BindingFlags.NonPublic).Invoke(panel,new object[]{new DragEventArgs(data,0,0,0,DragDropEffects.Copy,DragDropEffects.Copy)});} }
 static int checks;static void Check(bool ok,string message){if(!ok)throw new Exception(message);checks++;Console.WriteLine("PASS "+message);}
 [STAThread]static void Main(){try{Application.EnableVisualStyles();string selected=null;string[] sent=null;var peers=new[]{new Device{id="peer",name="Other PC"}};using(var panel=new TransferPopup()){panel.ConfigureDrop(()=>peers,(id,files)=>{selected=id;sent=files;});panel.Show();Application.DoEvents();var paths=new[]{@"C:\first.txt",@"C:\second.png"};DropProbe.Drop(panel,paths);Check(selected=="peer"&&sent.SequenceEqual(paths),"OLE drop routes all files to the connected PC");selected=null;peers=new Device[0];DropProbe.Drop(panel,paths);Check(selected==null,"offline destination never receives a drop");panel.Place(new Rectangle(-1920,0,1920,1040));Check(panel.Right==-20&&panel.Bottom==1020,"corner placement respects secondary monitor coordinates");var status=new TransferStatus{Name="Clipboard-report.pdf",Message="Sending",Total=100,Done=40};panel.UpdateTransfer(status);var field=typeof(TransferPopup).GetField("current",BindingFlags.NonPublic|BindingFlags.Instance);Check(field.GetValue(panel)==status,"real filenames beginning with Clipboard show progress");var second=new TransferStatus{Name="second.bin",Message="Receiving",Total=200};panel.UpdateTransfer(second);Check(field.GetValue(panel)==status,"concurrent updates do not replace an active transfer");status.Finished=true;for(int i=0;i<30;i++){Application.DoEvents();System.Threading.Thread.Sleep(10);}Check(field.GetValue(panel)==second,"next active transfer is displayed after completion");panel.Place(Screen.PrimaryScreen.WorkingArea);using(var image=new Bitmap(panel.Width,panel.Height)){panel.DrawToBitmap(image,panel.ClientRectangle);image.Save("build/file-transfer-progress.png");}}
 using(var corners=new TransferCorners(()=>new Device[0],(id,files)=>{})){Application.DoEvents();Check(!corners.Visible&&!Application.OpenForms.OfType<TransferPopup>().Any(p=>p.Visible),"transfer panels start hidden");corners.SetVisible(true);Application.DoEvents();var panels=Application.OpenForms.OfType<TransferPopup>().ToArray();Check(panels.Length==Screen.AllScreens.Length&&panels.All(p=>p.Visible),"menu can show drop panels on every monitor");var active=new TransferStatus{Name="active.bin",Message="Sending",Total=100};corners.UpdateTransfer(active);panels[0].Controls.OfType<SoftButton>().First(b=>b.Name=="DismissTransfer").PerformClick();for(int i=0;i<120;i++){Application.DoEvents();System.Threading.Thread.Sleep(10);}corners.UpdateTransfer(active);Check(!corners.Visible&&panels.All(p=>!p.Visible)&&!active.Cancel.IsCancellationRequested,"close survives refresh and progress without cancelling transfer");corners.SetVisible(true);Check(panels.All(p=>p.Visible),"dismissed panels can be reopened");corners.SetVisible(false);}
 using(var restored=new TransferCorners(()=>new Device[0],(id,files)=>{}))Check(!restored.Visible,"dismissal survives a new desk session");
 Check(!Application.OpenForms.OfType<TransferPopup>().Any(),"disconnect disposes every corner panel");Console.WriteLine(checks+" file drop checks passed");}catch(Exception e){Console.Error.WriteLine(e);Environment.ExitCode=1;}}
}
