using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Drawing;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using System.Security.Cryptography;
using Velixa;
public static class SharingRegression {
 static int checks;static void Check(bool ok,string message){if(!ok)throw new Exception(message);checks++;Console.WriteLine("PASS "+message);}
 static Dictionary<string,object> Message(object value){return Wire.Parse(Wire.Json(value));}
 [STAThread]static void Main(){try{Run();Console.WriteLine(checks+" sharing checks passed");}catch(Exception e){Console.Error.WriteLine(e);Environment.ExitCode=1;}}
 static void Run(){string root=Path.Combine(Wire.DataDir,"sharing-tests"),dest=Path.Combine(root,"received");Directory.CreateDirectory(root);ShareService a=null,b=null;var received=new List<string>();var statuses=new List<TransferStatus>();string format=null;byte[] clipboard=null;bool corrupt=false,cancelNext=false;
 a=new ShareService((peer,m)=>{var wire=Message(m);if(corrupt&&Wire.S(wire,"kind")=="end")wire["hash"]=new string('0',64);b.Handle("sender",wire);},action=>action(),()=>new[]{"receiver"},Path.Combine(root,"sender"),false);
 b=new ShareService((peer,m)=>a.Handle("receiver",Message(m)),action=>action(),()=>new[]{"sender"},dest,false);
 b.ReceivedFile=(peer,path)=>{lock(received)received.Add(path);};b.ReceivedClipboard=(type,bytes)=>{format=type;clipboard=bytes;};a.Progress=s=>{lock(statuses){if(s.Finished)statuses.Add(s);}if(cancelNext&&!s.Finished){s.Cancel.Cancel();cancelNext=false;}};
 using(a)using(b){byte[] payload=new byte[2*1024*1024+173];new Random(93).NextBytes(payload);string file=Path.Combine(root,"résumé.bin");File.WriteAllBytes(file,payload);Check(a.SendFiles("receiver",new[]{file}).Wait(30000),"multi-chunk transfer finishes");Check(received.Count==1&&File.ReadAllBytes(received[0]).SequenceEqual(payload),"binary file byte-for-byte verified");a.SendFiles("receiver",new[]{file}).Wait();Check(received.Count==2&&received[0]!=received[1],"duplicate filename does not overwrite");File.WriteAllBytes(Path.Combine(root,"empty.txt"),new byte[0]);a.SendFiles("receiver",new[]{Path.Combine(root,"empty.txt")}).Wait();Check(received.Count==3&&new FileInfo(received[2]).Length==0,"empty file supported");var unicode=Encoding.UTF8.GetBytes("हैलो · clipboard\n"+new string('x',40000));a.SendClipboard("receiver","text",unicode).Wait();Check(format=="text"&&clipboard.SequenceEqual(unicode),"Unicode multiline clipboard across chunks");using(var image=new Bitmap(80,40))using(var memory=new MemoryStream()){image.Save(memory,System.Drawing.Imaging.ImageFormat.Png);var png=memory.ToArray();a.SendClipboard("receiver","png",png).Wait();Check(format=="png"&&clipboard.SequenceEqual(png),"image clipboard transfer");}
 corrupt=true;a.SendFiles("receiver",new[]{file}).Wait();Check(received.Count==3&&statuses.Last().Failed,"checksum corruption rejected");corrupt=false;cancelNext=true;a.SendFiles("receiver",new[]{file}).Wait();Check(statuses.Last().Failed&&received.Count==3,"sender cancellation prevents commit");b.FilesEnabled=false;a.SendFiles("receiver",new[]{file}).Wait();Check(statuses.Last().Failed,"receiver can disable file sharing");b.FilesEnabled=true;b.ClipboardEnabled=false;clipboard=null;a.SendClipboard("receiver","text",unicode).Wait();Check(clipboard==null&&statuses.Last().Failed,"receiver can disable clipboard sharing");
 Check(!ShareService.SafeName("../escape.txt")&&!ShareService.SafeName("C:\\escape.txt")&&!ShareService.SafeName("file.txt:stream")&&!ShareService.SafeName("CON.txt")&&!ShareService.SafeName("trailing."),"traversal, ADS and reserved names rejected");Check(ShareService.SafeName("holiday photo.png"),"ordinary filenames accepted");Check(SpinWait.SpinUntil(()=>!Directory.GetFiles(dest,"*.partial").Any(),3000),"failed transfers leave no partial files");Check(statuses.Any(s=>!s.Failed&&s.Done==s.Total&&s.Total==payload.Length),"large transfer progress reaches total");}
 var outbound=new List<Dictionary<string,object>>();using(var microphone=new MicrophoneShare((to,m)=>outbound.Add(Message(m)),action=>action(),id=>true)){string id=Guid.NewGuid().ToString("N");microphone.Handle("peer",Message(new{kind="mic-begin",id=id,rate=48000,channels=1,bits=16}));Check(outbound.Count==1&&Wire.S(outbound[0],"ok")=="False"&&!microphone.Receiving,"microphone receiving requires opt-in");microphone.ReceiveEnabled=true;microphone.OutputDevice=0;outbound.Clear();microphone.Handle("peer",Message(new{kind="mic-begin",id=id,rate=1,channels=100,bits=7}));Check(outbound.Count==1&&Wire.S(outbound[0],"ok")=="False","invalid microphone formats rejected");microphone.Handle("peer",Message(new{kind="mic-data",id=id,data="invalid"}));Check(!microphone.Receiving,"unsolicited microphone packets ignored");Check(!microphone.Sending,"remote packets cannot enable capture");}
 var input=WaveAudio.Devices(true);var output=WaveAudio.Devices(false);Console.WriteLine("Audio devices: "+input.Length+" capture, "+output.Length+" output");Check(!ShareService.ValidPng(new byte[24]),"malformed clipboard image rejected before decoding");Check(input.All(d=>!String.IsNullOrEmpty(d.Name))&&output.All(d=>!String.IsNullOrEmpty(d.Name)),"audio device enumeration");
 if(input.Length>0){long bytes=0;using(var cancel=new CancellationTokenSource(3000)){WaveAudio.Capture(input[0].Id,data=>bytes+=data.Length,cancel.Token);}Check(bytes>0,"native microphone opens and produces PCM buffers without saving audio");}
 if(output.Length>0){using(var samples=new System.Collections.Concurrent.BlockingCollection<byte[]>(8))using(var cancel=new CancellationTokenSource(2000)){samples.Add(new byte[3840]);try{WaveAudio.Play(output[0].Id,samples,cancel.Token,()=>{});}catch(OperationCanceledException){}}Check(true,"native output accepts silent PCM and closes cleanly");}
 if(input.Length>0&&output.Length>0){var pending=new System.Collections.Concurrent.ConcurrentQueue<Action>();MicrophoneShare sender=null,receiver=null;int packets=0;sender=new MicrophoneShare((to,body)=>{var m=Message(body);if(Wire.S(m,"kind")=="mic-data"){packets++;m["data"]=Convert.ToBase64String(new byte[Convert.FromBase64String(Wire.S(m,"data")).Length]);}receiver.Handle("sender",m);},action=>pending.Enqueue(action),id=>true);receiver=new MicrophoneShare((to,body)=>sender.Handle("receiver",Message(body)),action=>pending.Enqueue(action),id=>true);using(sender)using(receiver){receiver.ReceiveEnabled=true;receiver.OutputDevice=output[0].Id;sender.AllowRemoteRequests=true;receiver.RequestRemoteMic("sender",input[0].Id);var end=DateTime.UtcNow.AddSeconds(5);Action action;while(DateTime.UtcNow<end&&packets<12){while(pending.TryDequeue(out action))action();Thread.Sleep(10);}Check(packets>=12&&sender.Sending&&receiver.Receiving,"microphone negotiation and live PCM packet delivery");sender.StopSending();receiver.StopReceiving();end=DateTime.UtcNow.AddMilliseconds(300);while(DateTime.UtcNow<end){while(pending.TryDequeue(out action))action();Thread.Sleep(10);}Check(!sender.Sending&&!receiver.Receiving,"microphone stop releases both endpoints");}}

 }
}
