package com.velixa.app;
import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.*;
import com.google.zxing.*;
import com.google.zxing.common.*;
public final class Smoke extends Instrumentation {
 Bundle args;public void onCreate(Bundle args){this.args=args;start();}
 void check(boolean ok,String name)throws Exception{if(!ok)throw new Exception(name);}
 boolean flag(String id,String key,boolean wanted)throws Exception{long end=System.currentTimeMillis()+10000;while(System.currentTimeMillis()<end){for(int i=0;i<InputService.deskDevices.length();i++){org.json.JSONObject d=InputService.deskDevices.optJSONObject(i);if(d.optString("id").equals(id)&&d.optBoolean(key)==wanted)return true;}Thread.sleep(150);}return false;}
 public void onStart(){Bundle result=new Bundle();try{Bitmap bitmap=BitmapFactory.decodeFile(args.getString("image"));check(bitmap!=null,"QR image loaded");int[] pixels=new int[bitmap.getWidth()*bitmap.getHeight()];bitmap.getPixels(pixels,0,bitmap.getWidth(),0,0,bitmap.getWidth(),bitmap.getHeight());String qr=new MultiFormatReader().decode(new BinaryBitmap(new HybridBinarizer(new RGBLuminanceSource(bitmap.getWidth(),bitmap.getHeight(),pixels)))).getText();check(qr.startsWith("velixa://pair/"),"Windows QR decodes on Android");
 MainActivity activity=(MainActivity)startActivitySync(new Intent(getTargetContext(),MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));waitForIdleSync();getUiAutomation(UiAutomation.FLAG_DONT_SUPPRESS_ACCESSIBILITY_SERVICES).executeShellCommand("settings put secure enabled_accessibility_services null").close();Thread.sleep(400);getUiAutomation(UiAutomation.FLAG_DONT_SUPPRESS_ACCESSIBILITY_SERVICES).executeShellCommand("settings put secure enabled_accessibility_services com.velixa.app/.InputService").close();long serviceDeadline=System.currentTimeMillis()+8000;while(InputService.instance==null&&System.currentTimeMillis()<serviceDeadline)Thread.sleep(200);check(InputService.instance!=null,"Accessibility service connected");runOnMainSync(()->activity.onActivityResult(42,Activity.RESULT_OK,new Intent().putExtra("qr",qr)));long deadline=System.currentTimeMillis()+12000;while(!InputService.online&&System.currentTimeMillis()<deadline)Thread.sleep(200);check(InputService.online,"QR authenticated connection: "+InputService.state);check(InputService.deskDevices.length()>=2,"Shared desk received");String id=getTargetContext().getSharedPreferences("velixa",0).getString("id","");InputService.instance.positionDevice(id,244,-90);boolean positioned=false;deadline=System.currentTimeMillis()+6000;while(!positioned&&System.currentTimeMillis()<deadline){for(int i=0;i<InputService.deskDevices.length();i++){org.json.JSONObject d=InputService.deskDevices.optJSONObject(i);if(d.optString("id").equals(id)&&Math.abs(d.optDouble("x")-220)<1&&d.optInt("y")==-90)positioned=true;}Thread.sleep(150);}check(positioned,"Android X and Y layout sync");check(SecureStore.get(getTargetContext()).contains("token")&&!SecureStore.get(getTargetContext()).contains("initial"),"One-use QR exchanged for saved credential");runOnMainSync(()->{InputService.instance.disconnect(false);InputService.instance.connect();});deadline=System.currentTimeMillis()+12000;while(!InputService.online&&System.currentTimeMillis()<deadline)Thread.sleep(200);check(InputService.online,"Pinned reconnection");InputService.instance.connection.send(new org.json.JSONObject().put("t","sleep").put("id",id).put("sleeping",true));check(flag(id,"sleeping",true),"Manual sleep synchronized");InputService.instance.connection.send(new org.json.JSONObject().put("t","sleep").put("id",id).put("sleeping",false));check(flag(id,"sleeping",false),"Wake keeps pairing");getUiAutomation(UiAutomation.FLAG_DONT_SUPPRESS_ACCESSIBILITY_SERVICES).executeShellCommand("input keyevent 223").close();check(flag(id,"awake",false),"Screen off automatically sleeps");getUiAutomation(UiAutomation.FLAG_DONT_SUPPRESS_ACCESSIBILITY_SERVICES).executeShellCommand("input keyevent 224").close();check(flag(id,"awake",true),"Screen on automatically wakes");android.media.AudioDeviceInfo[] microphones=MicrophoneService.devices(getTargetContext());check(microphones.length>0,"Android microphones enumerated");
 runOnMainSync(()->getTargetContext().startForegroundService(new Intent(getTargetContext(),MicrophoneService.class)));Thread.sleep(1000);check(MicrophoneService.instance!=null,"Visible microphone service enabled");
 String hostId=InputService.instance.connection.hostId;final int micId=microphones[0].getId();runOnMainSync(()->{try{MicrophoneService.handle(getTargetContext(),hostId,new org.json.JSONObject().put("kind","mic-request").put("id",MicrophoneService.fresh()).put("devId",micId));}catch(Exception e){throw new RuntimeException(e);}});Thread.sleep(4000);runOnMainSync(()->getTargetContext().stopService(new Intent(getTargetContext(),MicrophoneService.class)));Thread.sleep(300);check(MicrophoneService.instance==null,"Android microphone stop clears service");
 result.putString("stream","13 Android checks passed: QR decode, authenticated connection, shared desk, X/Y sync, credential exchange, pinned reconnect, manual sleep and wake, automatic screen sleep and wake.\n");finish(Activity.RESULT_OK,result);
 }catch(Exception e){result.putString("stream","FAIL "+e.toString());finish(Activity.RESULT_CANCELED,result);}}
}
