package com.velixa.app;
import android.content.Context;
import android.graphics.*;
import android.view.*;
import org.json.*;
public final class DeskView extends View {
 Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);int fg,muted,accent,surface;float scale=1,ox,oy,startX,startY;double oldX,oldY;JSONObject selected;boolean dragging;
 public DeskView(Context c,int fg,int muted,int accent,int surface){super(c);this.fg=fg;this.muted=muted;this.accent=accent;this.surface=surface;setContentDescription("Desk layout. Drag screens horizontally or vertically to position them.");}
 RectF bounds(JSONObject d){float w=d.optInt("w",1920),h=d.optInt("h",1080),factor=220/Math.max(w,h);float x=(float)d.optDouble("x"),y=(float)d.optDouble("y");return new RectF(x,y,x+w*factor,y+h*factor);}
 RectF card(JSONObject d){RectF r=bounds(d);return new RectF(ox+r.left*scale,oy+r.top*scale,ox+r.right*scale,oy+r.bottom*scale);}
 @Override protected void onDraw(Canvas c){super.onDraw(c);JSONArray devices=InputService.deskDevices;if(devices==null||devices.length()==0)return;if(!dragging){RectF all=new RectF();for(int i=0;i<devices.length();i++){RectF r=bounds(devices.optJSONObject(i));if(i==0)all.set(r);else all.union(r);}scale=Math.min((getWidth()-32)/(all.width()+40),(getHeight()-48)/(all.height()+40));ox=getWidth()/2f-all.centerX()*scale;oy=getHeight()/2f-all.centerY()*scale;}
  for(int i=0;i<devices.length();i++){JSONObject d=devices.optJSONObject(i);RectF r=card(d);boolean online=InputService.online&&d.optBoolean("online");boolean source=d.optString("id").equals(InputService.deskSource);p.setColor(accent);p.setAlpha(online?source?70:30:12);p.setStyle(Paint.Style.FILL);c.drawRoundRect(r,12,12,p);p.setAlpha(255);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(2);p.setColor(online?accent:muted);c.drawRoundRect(r,12,12,p);p.setStyle(Paint.Style.FILL);p.setTextAlign(Paint.Align.CENTER);p.setTextSize(Math.max(20,Math.min(32,24*scale)));p.setColor(online?fg:muted);String name=d.optString("name");while(name.length()>4&&p.measureText(name)>r.width()-10)name=name.substring(0,name.length()-2)+"…";c.drawText(name,r.centerX(),r.centerY()-4,p);p.setTextSize(Math.max(17,Math.min(25,18*scale)));c.drawText(!online?"Offline":source?"Input source":d.optString("kind"),r.centerX(),r.centerY()+28,p);}
 }
 @Override public boolean onTouchEvent(MotionEvent e){if(!InputService.online)return false;JSONArray devices=InputService.deskDevices;if(e.getAction()==MotionEvent.ACTION_DOWN){selected=null;for(int i=0;i<devices.length();i++)if(card(devices.optJSONObject(i)).contains(e.getX(),e.getY()))selected=devices.optJSONObject(i);if(selected==null)return false;startX=e.getX();startY=e.getY();oldX=selected.optDouble("x");oldY=selected.optDouble("y");dragging=true;getParent().requestDisallowInterceptTouchEvent(true);return true;}if(selected==null)return false;if(e.getAction()==MotionEvent.ACTION_MOVE){try{selected.put("x",Math.max(-5000,Math.min(5000,oldX+(e.getX()-startX)/scale)));selected.put("y",Math.max(-5000,Math.min(5000,oldY+(e.getY()-startY)/scale)));}catch(Exception ignored){}invalidate();return true;}if(e.getAction()==MotionEvent.ACTION_UP||e.getAction()==MotionEvent.ACTION_CANCEL){if(e.getAction()==MotionEvent.ACTION_UP&&InputService.instance!=null)InputService.instance.positionDevice(selected.optString("id"),selected.optDouble("x"),selected.optDouble("y"));dragging=false;selected=null;getParent().requestDisallowInterceptTouchEvent(false);invalidate();return true;}return true;}
}
