package com.velixa.app;
import android.content.Context;
import android.graphics.*;
import android.view.*;
import org.json.*;
public final class DeskView extends View {
 Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);int fg,muted,accent,surface;float scale=1,ox,oy,startX,startY;double oldX,oldY;JSONObject selected;boolean dragging;
 public DeskView(Context c,int fg,int muted,int accent,int surface){super(c);this.fg=fg;this.muted=muted;this.accent=accent;this.surface=surface;setContentDescription("Desk layout. Drag screens horizontally or vertically to position them.");}
 RectF bounds(JSONObject d){float w=d.optInt("w",1920),h=d.optInt("h",1080),factor=(float)(220*Math.max(.25,Math.min(3,d.optDouble("scale",1)))/Math.max(w,h));float x=(float)d.optDouble("x"),y=(float)d.optDouble("y");return new RectF(x,y,x+w*factor,y+h*factor);}
 RectF card(JSONObject d){RectF r=bounds(d);return new RectF(ox+r.left*scale,oy+r.top*scale,ox+r.right*scale,oy+r.bottom*scale);}
 @Override protected void onDraw(Canvas c){super.onDraw(c);JSONArray devices=InputService.deskDevices;if(devices==null||devices.length()==0)return;if(!dragging){RectF all=new RectF();for(int i=0;i<devices.length();i++){RectF r=bounds(devices.optJSONObject(i));if(i==0)all.set(r);else all.union(r);}scale=Math.min((getWidth()-32)/(all.width()+40),(getHeight()-48)/(all.height()+40));ox=getWidth()/2f-all.centerX()*scale;oy=getHeight()/2f-all.centerY()*scale;}
  for(int i=0;i<devices.length();i++){JSONObject d=devices.optJSONObject(i);RectF r=card(d);r.inset(Math.min(8,r.width()/6),Math.min(8,r.height()/6));boolean online=InputService.online&&d.optBoolean("online")&&!d.optBoolean("sleeping")&&d.optBoolean("awake",true);boolean source=d.optString("id").equals(InputService.deskSource);boolean local=d.optString("id").equals(getContext().getSharedPreferences("velixa",0).getString("id",""));int deviceColor=local?Color.rgb(236,190,75):Color.rgb(87,161,240);p.setColor(deviceColor);p.setAlpha(online?65:25);p.setStyle(Paint.Style.FILL);c.drawRoundRect(r,12,12,p);p.setAlpha(255);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(2);p.setColor(deviceColor);c.drawRoundRect(r,12,12,p);p.setStyle(Paint.Style.FILL);p.setTextAlign(Paint.Align.CENTER);p.setTypeface(Typeface.DEFAULT_BOLD);String number=String.valueOf(i+1);float size=Math.min(64*getResources().getDisplayMetrics().density,Math.min(r.width()*.6f,r.height()*.5f));p.setTextSize(size);if(p.measureText(number)>r.width()-8)p.setTextSize(size*(r.width()-8)/p.measureText(number));p.setColor(online?fg:muted);c.drawText(number,r.centerX(),r.centerY()-(p.ascent()+p.descent())/2,p);}

 }
 void send(JSONObject m){InputService service=InputService.instance;if(service==null||service.connection==null)return;final Connection connection=service.connection;new Thread(()->connection.send(m)).start();}
 void options(JSONObject d){new android.app.AlertDialog.Builder(getContext()).setTitle(d.optString("name")).setItems(new String[]{d.optBoolean("sleeping")?"Wake in Velixa":"Put to sleep in Velixa","Adjust screen size"},(dialog,index)->{try{if(index==0)send(new JSONObject().put("t","sleep").put("id",d.optString("id")).put("sleeping",!d.optBoolean("sleeping")));else{android.widget.LinearLayout layout=new android.widget.LinearLayout(getContext());layout.setOrientation(1);layout.setPadding(32,24,32,24);android.widget.TextView value=new android.widget.TextView(getContext());android.widget.SeekBar size=new android.widget.SeekBar(getContext());size.setMax(275);size.setProgress((int)(d.optDouble("scale",1)*100)-25);value.setText((size.getProgress()+25)+"% · proportions stay the same");layout.addView(value);layout.addView(size);size.setOnSeekBarChangeListener(new android.widget.SeekBar.OnSeekBarChangeListener(){public void onStartTrackingTouch(android.widget.SeekBar b){}public void onStopTrackingTouch(android.widget.SeekBar b){}public void onProgressChanged(android.widget.SeekBar b,int n,boolean user){value.setText((n+25)+"% · proportions stay the same");}});new android.app.AlertDialog.Builder(getContext()).setTitle("Screen size").setView(layout).setNegativeButton("Cancel",null).setPositiveButton("Apply",(a,b)->{try{send(new JSONObject().put("t","scale").put("id",d.optString("id")).put("scale",(size.getProgress()+25)/100d));}catch(Exception ignored){}}).show();}}catch(Exception ignored){}}).show();}
 @Override public boolean onTouchEvent(MotionEvent e){if(!InputService.online)return false;JSONArray devices=InputService.deskDevices;if(e.getAction()==MotionEvent.ACTION_DOWN){selected=null;for(int i=0;i<devices.length();i++)if(card(devices.optJSONObject(i)).contains(e.getX(),e.getY()))selected=devices.optJSONObject(i);if(selected==null)return false;startX=e.getX();startY=e.getY();oldX=selected.optDouble("x");oldY=selected.optDouble("y");dragging=true;getParent().requestDisallowInterceptTouchEvent(true);return true;}if(selected==null)return false;if(e.getAction()==MotionEvent.ACTION_MOVE){try{selected.put("x",Math.max(-5000,Math.min(5000,oldX+(e.getX()-startX)/scale)));selected.put("y",Math.max(-5000,Math.min(5000,oldY+(e.getY()-startY)/scale)));}catch(Exception ignored){}invalidate();return true;}if(e.getAction()==MotionEvent.ACTION_UP||e.getAction()==MotionEvent.ACTION_CANCEL){if(e.getAction()==MotionEvent.ACTION_UP&&InputService.instance!=null){if(Math.abs(e.getX()-startX)+Math.abs(e.getY()-startY)<8)options(selected);else InputService.instance.positionDevice(selected.optString("id"),selected.optDouble("x"),selected.optDouble("y"));}else if(e.getAction()==MotionEvent.ACTION_CANCEL){try{selected.put("x",oldX);selected.put("y",oldY);}catch(Exception ignored){}}dragging=false;selected=null;getParent().requestDisallowInterceptTouchEvent(false);invalidate();return true;}return true;}
}
