package com.velixa.app;
import android.accessibilityservice.*;
import android.content.*;
import android.graphics.*;
import android.os.*;
import android.view.*;
import android.view.accessibility.*;
import org.json.JSONObject;
import java.util.*;

public final class InputService extends AccessibilityService implements Connection.Listener {
 public static volatile org.json.JSONArray deskDevices=new org.json.JSONArray();public static volatile String deskSource="";public static volatile boolean online=false;
 public static volatile InputService instance;public static volatile String state="Enable continuity to connect";
 final Handler main=new Handler(Looper.getMainLooper());Connection connection;WindowManager wm;Overlay overlay;boolean active=false;float x,y;Path drag;long downAt;int points;boolean gestureBusy;int generation;final ArrayDeque<GestureDescription> gestures=new ArrayDeque<>();
 @Override protected void onServiceConnected(){instance=this;wm=(WindowManager)getSystemService(WINDOW_SERVICE);if(Build.VERSION.SDK_INT>=33){AccessibilityServiceInfo info=getServiceInfo();info.flags|=AccessibilityServiceInfo.FLAG_INPUT_METHOD_EDITOR;setServiceInfo(info);}overlay=new Overlay(this);WindowManager.LayoutParams p=new WindowManager.LayoutParams(-1,-1,WindowManager.LayoutParams.TYPE_ACCESSIBILITY_OVERLAY,WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE|WindowManager.LayoutParams.FLAG_NOT_TOUCHABLE|WindowManager.LayoutParams.FLAG_LAYOUT_IN_SCREEN|WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS,PixelFormat.TRANSLUCENT);p.gravity=Gravity.TOP|Gravity.LEFT;if(Build.VERSION.SDK_INT>=28)p.layoutInDisplayCutoutMode=WindowManager.LayoutParams.LAYOUT_IN_DISPLAY_CUTOUT_MODE_SHORT_EDGES;wm.addView(overlay,p);state="Continuity enabled · ready to pair";if(getSharedPreferences("velixa",0).getBoolean("connected",false))connect();}
 public void connect(){disconnect(false);String host=getSharedPreferences("velixa",0).getString("host",""),secret=SecureStore.get(this);if(host.isEmpty()||!secret.startsWith("{")){getSharedPreferences("velixa",0).edit().putBoolean("connected",false).apply();state="Scan your PC’s QR code in Velixa";return;}String id=getSharedPreferences("velixa",0).getString("id","");if(id.isEmpty()){id=UUID.randomUUID().toString();getSharedPreferences("velixa",0).edit().putString("id",id).apply();}final int token=generation;connection=new Connection(this,host,secret,id,new Connection.Listener(){public int width(){return InputService.this.width();}public int height(){return InputService.this.height();}public void status(String s){if(token==generation)state=s;}public void message(JSONObject m){main.post(()->{if(token==generation&&connection!=null)handle(m);});}});getSharedPreferences("velixa",0).edit().putBoolean("connected",true).apply();connection.start();}
 public void disconnect(boolean remember){generation++;online=false;if(connection!=null){connection.stop();connection=null;}active=false;drag=null;gestures.clear();if(overlay!=null)overlay.invalidate();if(remember)getSharedPreferences("velixa",0).edit().putBoolean("connected",false).apply();state="Disconnected";}
 @Override public void onDestroy(){disconnect(false);instance=null;if(overlay!=null)try{wm.removeView(overlay);}catch(Exception ignored){}super.onDestroy();}
 @Override public void onInterrupt(){disconnect(true);}
 @Override public void onAccessibilityEvent(AccessibilityEvent event){}
 @Override public void status(String s){state=s;}
 @Override public int width(){Point p=new Point();((WindowManager)getSystemService(WINDOW_SERVICE)).getDefaultDisplay().getRealSize(p);return p.x;}
 @Override public int height(){Point p=new Point();((WindowManager)getSystemService(WINDOW_SERVICE)).getDefaultDisplay().getRealSize(p);return p.y;}
 @Override public void message(JSONObject m){main.post(()->handle(m));}
 void handle(JSONObject m){String t=m.optString("t");if(t.equals("desk")){deskDevices=m.optJSONArray("devices");deskSource=m.optString("source");online=true;return;}if(t.equals("offline")){online=false;active=false;drag=null;gestures.clear();overlay.invalidate();return;}if(t.equals("leave")){overlay.edgeFrom=(float)m.optDouble("edgeFrom",0);overlay.edgeTo=(float)m.optDouble("edgeTo",1);if(active)flash(m.optString("edge","right"));active=false;drag=null;gestures.clear();overlay.invalidate();if(state.equals("You’re controlling this device"))state="Connected · ready for your pointer";return;}if(t.equals("enter")){if(!((PowerManager)getSystemService(POWER_SERVICE)).isInteractive())return;overlay.edgeFrom=(float)m.optDouble("edgeFrom",0);overlay.edgeTo=(float)m.optDouble("edgeTo",1);active=true;position(m);flash(m.optString("edge","left"));state="You’re controlling this device";return;}if(!active||!((PowerManager)getSystemService(POWER_SERVICE)).isInteractive())return;
  if(t.equals("move")){position(m);if(drag!=null&&points++<2000)drag.lineTo(x,y);}
  if(t.equals("button")){int b=m.optInt("button");boolean down=m.optBoolean("down");if(b==2&&down){performGlobalAction(GLOBAL_ACTION_BACK);return;}if(b==3&&down){performGlobalAction(GLOBAL_ACTION_HOME);return;}if(b==1){if(down){drag=new Path();drag.moveTo(x,y);downAt=SystemClock.uptimeMillis();points=0;}else if(drag!=null){Path p=drag;drag=null;long duration=Math.max(40,Math.min(4000,SystemClock.uptimeMillis()-downAt));gesture(p,duration);}}}
  if(t.equals("wheel")){Path p=new Path();float amount=m.optInt("delta")>0?height()*.22f:-height()*.22f;float startY=Math.max(height()*.25f,Math.min(height()*.75f,y));p.moveTo(x,startY);p.lineTo(x,Math.max(20,Math.min(height()-20,startY+amount)));gesture(p,160);}
  if(t.equals("key"))key(m);
 }
 public void positionDevice(String id,double px,double py){final Connection current=connection;if(current==null||!online)return;new Thread(()->{try{current.send(new JSONObject().put("t","layout").put("id",id).put("x",px).put("y",py));}catch(Exception ignored){}}).start();}
 void position(JSONObject m){x=(float)Math.max(0,Math.min(width()-1,m.optDouble("x",.5)*width()));y=(float)Math.max(0,Math.min(height()-1,m.optDouble("y",.5)*height()));overlay.invalidate();}
 void flash(String side){overlay.edge=side;overlay.flashUntil=SystemClock.uptimeMillis()+650;overlay.invalidate();}
 void gesture(Path path,long duration){if(gestures.size()>=8)return;gestures.add(new GestureDescription.Builder().addStroke(new GestureDescription.StrokeDescription(path,0,duration)).build());nextGesture();}
 void nextGesture(){if(gestureBusy||gestures.isEmpty()||!active)return;gestureBusy=true;GestureDescription g=gestures.poll();boolean ok=dispatchGesture(g,new GestureResultCallback(){@Override public void onCompleted(GestureDescription d){gestureBusy=false;nextGesture();}@Override public void onCancelled(GestureDescription d){gestureBusy=false;gestures.clear();}},main);if(!ok){gestureBusy=false;gestures.clear();}}
 void key(JSONObject m){if(!m.optBoolean("down"))return;int vk=m.optInt("vk");String text=m.optString("text");boolean ctrl=m.optBoolean("ctrl"),shift=m.optBoolean("shift"),alt=m.optBoolean("alt");
  if(vk==27){performGlobalAction(GLOBAL_ACTION_BACK);return;}if(vk==91||vk==92){performGlobalAction(GLOBAL_ACTION_HOME);return;}if(alt&&vk==9){performGlobalAction(GLOBAL_ACTION_RECENTS);return;}
  int code=vk==8?KeyEvent.KEYCODE_DEL:vk==13?KeyEvent.KEYCODE_ENTER:vk==9?KeyEvent.KEYCODE_TAB:vk==37?KeyEvent.KEYCODE_DPAD_LEFT:vk==38?KeyEvent.KEYCODE_DPAD_UP:vk==39?KeyEvent.KEYCODE_DPAD_RIGHT:vk==40?KeyEvent.KEYCODE_DPAD_DOWN:vk==46?KeyEvent.KEYCODE_FORWARD_DEL:vk==36?KeyEvent.KEYCODE_MOVE_HOME:vk==35?KeyEvent.KEYCODE_MOVE_END:vk>=65&&vk<=90?KeyEvent.KEYCODE_A+vk-65:0;
  if(!text.isEmpty()&&!ctrl&&!alt){if(Build.VERSION.SDK_INT>=33&&getInputMethod()!=null&&getInputMethod().getCurrentInputConnection()!=null){getInputMethod().getCurrentInputConnection().commitText(text,1,null);return;}if(VelixaKeyboard.current!=null&&VelixaKeyboard.current.getCurrentInputConnection()!=null){VelixaKeyboard.current.getCurrentInputConnection().commitText(text,1);return;}state="Choose Velixa keyboard to type on this Android version";return;}
  if(code!=0){int meta=(ctrl?KeyEvent.META_CTRL_ON:0)|(shift?KeyEvent.META_SHIFT_ON:0)|(alt?KeyEvent.META_ALT_ON:0);long now=SystemClock.uptimeMillis();for(int action:new int[]{KeyEvent.ACTION_DOWN,KeyEvent.ACTION_UP}){KeyEvent e=new KeyEvent(now,now,action,code,0,meta,KeyCharacterMap.VIRTUAL_KEYBOARD,0,KeyEvent.FLAG_SOFT_KEYBOARD);if(Build.VERSION.SDK_INT>=33&&getInputMethod()!=null&&getInputMethod().getCurrentInputConnection()!=null)getInputMethod().getCurrentInputConnection().sendKeyEvent(e);else if(VelixaKeyboard.current!=null&&VelixaKeyboard.current.getCurrentInputConnection()!=null)VelixaKeyboard.current.getCurrentInputConnection().sendKeyEvent(e);}}
 }
 final class Overlay extends View {
  Paint paint=new Paint(Paint.ANTI_ALIAS_FLAG);String edge="left";long flashUntil;float edgeFrom=0,edgeTo=1;
  Overlay(Context c){super(c);setImportantForAccessibility(IMPORTANT_FOR_ACCESSIBILITY_NO);}
  @Override protected void onDraw(Canvas canvas){super.onDraw(canvas);long remaining=flashUntil-SystemClock.uptimeMillis();if(remaining>0){paint.setColor(Color.CYAN);paint.setAlpha((int)Math.min(255,remaining*255/450));float thick=6*getResources().getDisplayMetrics().density;if(edge.equals("left"))canvas.drawRect(0,getHeight()*edgeFrom,thick,getHeight()*edgeTo,paint);else if(edge.equals("right"))canvas.drawRect(getWidth()-thick,getHeight()*edgeFrom,getWidth(),getHeight()*edgeTo,paint);else if(edge.equals("top"))canvas.drawRect(getWidth()*edgeFrom,0,getWidth()*edgeTo,thick,paint);else canvas.drawRect(getWidth()*edgeFrom,getHeight()-thick,getWidth()*edgeTo,getHeight(),paint);postInvalidateDelayed(16);}paint.setAlpha(255);if(active){float d=getResources().getDisplayMetrics().density;Path p=new Path();p.moveTo(x,y);p.lineTo(x+4*d,y+21*d);p.lineTo(x+9*d,y+15*d);p.lineTo(x+17*d,y+14*d);p.close();paint.setColor(Color.WHITE);paint.setStyle(Paint.Style.FILL);canvas.drawPath(p,paint);paint.setColor(Color.rgb(35,31,55));paint.setStyle(Paint.Style.STROKE);paint.setStrokeWidth(1.5f*d);canvas.drawPath(p,paint);paint.setStyle(Paint.Style.FILL);}}
 }
}
