package com.velixa.app;
import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.provider.Settings;
import android.view.*;
import android.view.inputmethod.InputMethodManager;
import android.widget.*;
import java.util.*;
public final class MainActivity extends Activity {
 DeskView desk;LinearLayout root,setup,pair,connectionCard;TextView status,subtitle,deviceNames;EditText host,code;Button connect,access,mic;int bg=0xFFFFFBFE,fg=0xFF1D1B20,muted=0xFF625B71,surface=0xFFF0EBF4,accent=0xFF6750A4,onAccent=Color.WHITE;Handler timer=new Handler(Looper.getMainLooper());
 final Runnable refresh=new Runnable(){public void run(){if(status!=null){boolean enabled=InputService.instance!=null,linked=getSharedPreferences("velixa",0).getBoolean("connected",false);setLabel(status,InputService.state);if(mic!=null)setLabel(mic,MicrophoneService.instance==null?"Enable microphone sharing to PCs":"Stop microphone sharing");if(desk!=null)desk.invalidate();refreshDeviceNames();setLabel(access,enabled?"Continuity is enabled  ✓":"Enable continuity");setup.setVisibility(enabled?View.GONE:View.VISIBLE);pair.setVisibility(enabled&&!linked?View.VISIBLE:View.GONE);connectionCard.setVisibility(enabled&&linked?View.VISIBLE:View.GONE);setLabel(subtitle,linked?(InputService.online?"Drag to arrange. Tap a screen for sleep and size.":"Your desk will reconnect when nearby."):enabled?"Connect your main Windows PC.":"One keyboard. Every screen.");}timer.postDelayed(this,700);}};
 @Override public void onCreate(Bundle state){boolean dark=(getResources().getConfiguration().uiMode&0x30)==0x20;if(dark)setTheme(android.R.style.Theme_Material_NoActionBar);super.onCreate(state);if(!SecureStore.get(this).startsWith("{"))getSharedPreferences("velixa",0).edit().putBoolean("connected",false).apply();if(dark){bg=0xFF141218;fg=0xFFE6E0E9;muted=0xFFCAC4D0;surface=0xFF25222B;accent=0xFFD0BCFF;onAccent=0xFF381E72;}
 if(Build.VERSION.SDK_INT>=31){accent=getColor(dark?android.R.color.system_accent1_200:android.R.color.system_accent1_600);surface=getColor(dark?android.R.color.system_neutral1_900:android.R.color.system_neutral1_50);}
 getWindow().setStatusBarColor(bg);getWindow().setNavigationBarColor(bg);getWindow().getDecorView().setSystemUiVisibility(dark?0:View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR); if(Build.VERSION.SDK_INT>=30){android.view.WindowInsetsController bars=getWindow().getInsetsController();if(bars!=null)bars.setSystemBarsAppearance(dark?0:android.view.WindowInsetsController.APPEARANCE_LIGHT_STATUS_BARS|android.view.WindowInsetsController.APPEARANCE_LIGHT_NAVIGATION_BARS,android.view.WindowInsetsController.APPEARANCE_LIGHT_STATUS_BARS|android.view.WindowInsetsController.APPEARANCE_LIGHT_NAVIGATION_BARS);}
 ScrollView scroll=new ScrollView(this);scroll.setBackgroundColor(bg);scroll.setFillViewport(true);scroll.setOverScrollMode(View.OVER_SCROLL_NEVER);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(24),dp(24),dp(24),dp(32));scroll.addView(root);setContentView(scroll);root.setOnApplyWindowInsetsListener((v,insets)->{v.setPadding(dp(24),dp(20)+insets.getSystemWindowInsetTop(),dp(24),dp(24)+insets.getSystemWindowInsetBottom());return insets;});
 LinearLayout brand=new LinearLayout(this);brand.setGravity(Gravity.CENTER_VERTICAL);ImageView logo=new ImageView(this);logo.setImageResource(com.velixa.app.R.drawable.ic_mono);logo.setColorFilter(accent);brand.addView(logo,new LinearLayout.LayoutParams(dp(50),dp(50)));TextView title=text("Velixa",26,fg,true);LinearLayout.LayoutParams titleP=new LinearLayout.LayoutParams(-2,-2);titleP.leftMargin=dp(8);brand.addView(title,titleP);root.addView(brand);addText(root,"Your desk, together.",28,fg,true,24);subtitle=text("One keyboard. Every screen.",15,muted,false);space(subtitle,8);root.addView(subtitle);
 connectionCard=card(24);TextView local=text("●  YOUR DESK",11,accent,true);connectionCard.addView(local);status=text(InputService.state,19,fg,true);space(status,16);connectionCard.addView(status);
 setup=card(24);addText(setup,"Allow continuity",21,fg,true,0);addText(setup,"Let your paired PC move the pointer, tap and type on this device.",15,muted,false,12);access=button("Enable continuity",true,()->consent());space(access,24);setup.addView(access);
 pair=card(24);addText(pair,"Add this screen",21,fg,true,0);addText(pair,"On Windows, open Velixa → Add device. Scan the QR code to connect securely.",15,muted,false,12);Button scan=button("Scan QR code",true,()->startActivityForResult(new Intent(this,ScannerActivity.class),42));space(scan,24);pair.addView(scan);
 desk=new DeskView(this,fg,muted,accent,surface);LinearLayout.LayoutParams deskP=new LinearLayout.LayoutParams(-1,dp(210));deskP.topMargin=dp(20);connectionCard.addView(desk,deskP);deviceNames=text("",16,fg,false);deviceNames.setLineSpacing(dp(6),1);space(deviceNames,12);connectionCard.addView(deviceNames);Button position=button("Set X and Y position",false,()->positionDialog());space(position,12);connectionCard.addView(position);Button disconnect=button("Disconnect",false,()->toggle());space(disconnect,8);connectionCard.addView(disconnect);
 if(Build.VERSION.SDK_INT<33){LinearLayout keyboard=card(16);addText(keyboard,"3   Enable typing",19,fg,true,0);addText(keyboard,"On this Android version, select the Velixa keyboard while using your PC. You can switch back to your usual keyboard anytime.",14,muted,false,10);Button enable=button("Enable Velixa keyboard",false,()->startActivity(new Intent(Settings.ACTION_INPUT_METHOD_SETTINGS)));space(enable,12);keyboard.addView(enable);Button pick=button("Choose keyboard",false,()->((InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).showInputMethodPicker());space(pick,8);keyboard.addView(pick);}
 mic=button(MicrophoneService.instance==null?"Enable microphone sharing to PCs":"Stop microphone sharing",false,()->{if(MicrophoneService.instance!=null){stopService(new Intent(this,MicrophoneService.class));return;}if(checkSelfPermission(android.Manifest.permission.RECORD_AUDIO)!=android.content.pm.PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{android.Manifest.permission.RECORD_AUDIO},71);return;}startForegroundService(new Intent(this,MicrophoneService.class));});space(mic,16);root.addView(mic);
 Button help=button("How it works",false,()->new AlertDialog.Builder(this).setTitle("One desk, connected").setMessage("Drag screens in any direction in Windows or Android. Move the pointer across a screen edge to switch.\n\nClick → Tap\nRight-click → Back\nScroll → Swipe\nMiddle-click → Home\n\nCtrl + Alt + Backspace returns to your main PC.\n\nYour touchscreen stays local. No account or internet is needed.\n\nIf Accessibility is unavailable, open Velixa’s App info menu and allow restricted settings.").setPositiveButton("Got it",null).show());space(help,20);root.addView(help);
 addText(root,"LOCAL ONLY  ·  ENCRYPTED\nVelixa 0.5.1",11,muted,false,18);
 }
 int dp(int x){return (int)(x*getResources().getDisplayMetrics().density+.5f);}
 TextView text(String s,int size,int color,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setLineSpacing(dp(3),1);if(bold)t.setTypeface(Typeface.create("sans-serif-medium",Typeface.NORMAL));return t;}
 void addText(LinearLayout p,String s,int size,int color,boolean bold,int top){TextView t=text(s,size,color,bold);space(t,top);p.addView(t);}
 void space(View v,int top){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=dp(top);v.setLayoutParams(p);}
 GradientDrawable shape(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}
 LinearLayout card(int top){LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setPadding(dp(20),dp(20),dp(20),dp(20));p.setBackground(shape(surface,24));space(p,top);root.addView(p);return p;}
 Button button(String s,boolean primary,Runnable run){Button b=new Button(this);b.setText(s);b.setTextSize(14);b.setAllCaps(false);b.setTextColor(primary?onAccent:accent);b.setMinHeight(dp(50));b.setPadding(dp(18),dp(12),dp(18),dp(12));b.setBackground(shape(primary?accent:bg,28));b.setOnClickListener(v->run.run());return b;}
 EditText edit(String hint,String value,boolean secret){EditText t=new EditText(this);t.setTextSize(16);t.setSingleLine(true);t.setTextColor(fg);t.setHintTextColor(muted);t.setHint(hint);t.setText(value);t.setPadding(dp(16),dp(14),dp(16),dp(14));t.setBackground(shape(bg,12));t.setInputType(secret?android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_VARIATION_PASSWORD:android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_VARIATION_URI);t.setImportantForAutofill(View.IMPORTANT_FOR_AUTOFILL_NO);return t;}
 void consent(){new AlertDialog.Builder(this).setTitle("Allow Velixa continuity").setMessage("Velixa uses Android Accessibility to display a cursor and edge lights, perform the clicks and swipes you make, and enter text from your paired Windows keyboard. It can access the focused field to support typing.\n\nInput is received only from your paired PC over an encrypted local connection. Velixa does not record your screen, save keystrokes or send them to a cloud service.\n\nChoose Velixa continuity on the next screen and enable it.").setNegativeButton("Not now",null).setPositiveButton("Open settings",(d,w)->startActivity(new Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS))).show();}
 void toggle(){getSharedPreferences("velixa",0).edit().putBoolean("connected",false).apply();if(InputService.instance!=null)InputService.instance.disconnect(true);}
 @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request!=42||result!=RESULT_OK||data==null)return;try{String raw=data.getStringExtra("qr");if(raw==null||!raw.startsWith("velixa://pair/")||raw.length()>4096)throw new Exception();org.json.JSONObject q=new org.json.JSONObject(new String(android.util.Base64.decode(raw.substring(14),android.util.Base64.DEFAULT),"UTF-8"));String h=q.getString("host");if(q.getInt("v")!=2||!q.getString("fp").matches("[a-f0-9]{64}")||!q.getString("token").matches("[a-f0-9]{64}")||!privateAddress(h))throw new Exception();if(InputService.instance==null){consent();return;}q.put("initial",true);SecureStore.put(this,q.toString());getSharedPreferences("velixa",0).edit().putString("host",h).apply();InputService.instance.connect();}catch(Exception e){new AlertDialog.Builder(this).setTitle("Scan a new pairing code").setMessage("Open Add device on your Windows PC and scan its current Velixa QR code.").setPositiveButton("OK",null).show();}}
 static boolean privateAddress(String s){try{if(!s.matches("[0-9]{1,3}(\\.[0-9]{1,3}){3}"))return false;String[] p=s.split("\\.");int[] n=new int[4];for(int i=0;i<4;i++){n[i]=Integer.parseInt(p[i]);if(n[i]>255)return false;}return n[0]==10||n[0]==192&&n[1]==168||n[0]==172&&n[1]>=16&&n[1]<=31||n[0]==169&&n[1]==254;}catch(Exception e){return false;}}
 static void setLabel(TextView view,String text){if(!view.getText().toString().equals(text))view.setText(text);}
 void refreshDeviceNames(){if(deviceNames==null)return;org.json.JSONArray devices=InputService.deskDevices;StringBuilder labels=new StringBuilder();if(devices!=null)for(int i=0;i<devices.length();i++){if(i>0)labels.append("\n");org.json.JSONObject d=devices.optJSONObject(i);labels.append(i+1).append("  ").append(d.optString("name"));}String next=labels.toString();if(!deviceNames.getText().toString().equals(next))deviceNames.setText(next);}
 void positionDialog(){org.json.JSONArray devices=InputService.deskDevices;if(devices==null||devices.length()==0)return;String[] names=new String[devices.length()];for(int i=0;i<names.length;i++)names[i]=devices.optJSONObject(i).optString("name");new AlertDialog.Builder(this).setTitle("Position a screen").setItems(names,(d,index)->{org.json.JSONObject device=devices.optJSONObject(index);LinearLayout fields=new LinearLayout(this);fields.setOrientation(LinearLayout.VERTICAL);fields.setPadding(dp(24),dp(12),dp(24),dp(12));EditText x=edit("X",String.valueOf((int)device.optDouble("x")),false),y=edit("Y",String.valueOf((int)device.optDouble("y")),false);x.setInputType(android.text.InputType.TYPE_CLASS_NUMBER|android.text.InputType.TYPE_NUMBER_FLAG_SIGNED);y.setInputType(x.getInputType());addText(fields,"X · horizontal",14,muted,false,0);fields.addView(x);addText(fields,"Y · vertical",14,muted,false,12);fields.addView(y);new AlertDialog.Builder(this).setTitle(device.optString("name")).setView(fields).setNegativeButton("Cancel",null).setPositiveButton("Save",(a,b)->{try{double px=Double.parseDouble(x.getText().toString()),py=Double.parseDouble(y.getText().toString());if(InputService.instance!=null)InputService.instance.positionDevice(device.optString("id"),Math.max(-5000,Math.min(5000,px)),Math.max(-5000,Math.min(5000,py)));}catch(Exception ignored){Toast.makeText(this,"Enter a number for X and Y",Toast.LENGTH_SHORT).show();}}).show();}).show();}
 @Override public void onRequestPermissionsResult(int request,String[] permissions,int[] results){super.onRequestPermissionsResult(request,permissions,results);if(request==71&&results.length>0&&results[0]==android.content.pm.PackageManager.PERMISSION_GRANTED)startForegroundService(new Intent(this,MicrophoneService.class));}
 @Override protected void onResume(){super.onResume();timer.post(refresh);}
 @Override protected void onPause(){timer.removeCallbacks(refresh);super.onPause();}
}
